import React from "react";
import { Tool, ToolCategory } from "./types";
import {
  CaseIcon,
  CounterIcon,
  LoremIpsumIcon,
  Base64Icon,
  UrlIcon,
  JsonIcon,
  UuidIcon,
  PasswordIcon,
  ColorIcon,
  ImageIcon,
  TextReverseIcon,
  BoxShadowIcon,
  GradientIcon,
  BorderRadiusIcon,
  TextShadowIcon,
  GlassmorphismIcon,
  HashIcon,
  JwtIcon,
  QrCodeIcon,
  MarkdownIcon,
  DateCalcIcon,
  DiffIcon,
  PomodoroIcon,
  MemeIcon,
  RecipeIcon,
  RegexIcon,
  PaletteIcon,
  UnitConverterIcon,
  BmiIcon,
  TodoIcon,
  CurrencyIcon,
  WorldClockIcon,
  TimersIcon,
  FileConversionIcon,
  TextCategoryIcon,
  ImageCategoryIcon,
  CssCategoryIcon,
  CodeCategoryIcon,
  ColorCategoryIcon,
  MathCategoryIcon,
  ProductivityCategoryIcon,
  FunCategoryIcon,
  MiscCategoryIcon,
  VideoCategoryIcon,
  CharacterCounterIcon,
  KeywordDensityIcon,
  ReadabilityIcon,
  LoanCalculatorIcon,
  TimeZoneConverterIcon,
  VideoCompressorIcon,
  VideoToAudioIcon,
  GifMakerIcon,
  TrimVideoIcon,
  FormatConverterIcon,
  VideoThumbnailIcon,
  VideoMuteIcon,
  WatermarkAdderIcon,
  ImageResizerIcon,
  ImageConverterIcon,
  ImageCompressorIcon,
  CsvToJsonIcon,
  JsonToCsvIcon,
  CsvToXlsxIcon,
  XlsxToCsvIcon,
  Base64ToImageIcon,
  WordCounterIcon,
  TerminalIcon,
  CameraToolIcon,
  SqlIcon,
  CronIcon,
  Link2Icon,
  TagIcon,
  ContrastIcon,
  ChmodIcon,
  UtmIcon,
  TriangleIcon,
  XmlIcon,
  MorseIcon,
  BinaryIcon,
  ShieldCheckIcon,
  StringEscaperIcon,
  PercentIcon,
  TableIcon,
  ListIcon,
  EraserIcon,
  AspectRatioIcon,
  FileCodeIcon,
  YoutubeIcon,
  PenIcon,
  TagsIcon,
  FiltersIcon,
  BlobIcon,
  WavesIcon,
  KeyboardIcon,
  ScreenIcon,
  MicIcon,
  RomanIcon,
  BabyIcon,
  DiceIcon,
  DuplicateIcon,
  HtmlEntityIcon,
  CursorIcon,
  DevicesIcon,
  PlaceholderIcon,
  BorderIcon,
  PatternIcon,
  SignatureIcon,
  SeparatorIcon,
  AsciiIcon,
} from "@/components/icons";

const PRIVACY_STATEMENT =
  "All calculations and data processing for this tool are performed locally in your browser. We do not send any of your data to our servers, ensuring your information remains private and secure.";

export const TOOLS: Tool[] = [
  // ... existing tools
  {
    id: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Instantly generate TypeScript interfaces from JSON objects.",
    seoTitle: "JSON to TypeScript Converter | Generate Interfaces Instantly",
    seoDescription:
      "Convert JSON objects into TypeScript interfaces instantly. Our free online tool handles nested objects and arrays, saving you time. 100% private and secure.",
    icon: <JsonIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "json to typescript",
      "json to ts",
      "typescript interface generator",
      "json to types",
      "convert json to typescript",
      "json to interface",
    ],
  },
  {
    id: "code-to-image",
    name: "Code to Image",
    description: "Create beautiful images of your code snippets for sharing.",
    seoTitle: "Code to Image Converter | Create Beautiful Code Snippets",
    seoDescription:
      "Turn your code into beautiful, shareable images. Customize themes, fonts, and backgrounds with our free online Code to Image tool. Perfect for social media.",
    icon: <CameraToolIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "code to image",
      "code snippet image",
      "source code to image",
      "carbon alternative",
      "code screenshot generator",
      "syntax highlighting image",
    ],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify your SQL queries.",
    seoTitle: "Online SQL Formatter | Beatify & Format SQL Queries",
    seoDescription:
      "Format and beautify your SQL queries instantly online. Support for MySQL, PostgreSQL, SQL Server, and more. Clean up messy code with our free SQL Formatter.",
    icon: <SqlIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "sql formatter",
      "sql beautifier",
      "format sql online",
      "prettify sql",
      "sql syntax highlighter",
      "sql query formatter",
    ],
  },
  {
    id: "cron-generator",
    name: "Cron Expression Generator",
    description: "Visually build and explain cron job schedules.",
    seoTitle: "Cron Expression Generator | Visual Cron Job Editor",
    seoDescription:
      "Create and learn cron expressions with our easy-to-use visual generator. Schedule jobs for Linux/Unix systems without syntax errors. Free and instant.",
    icon: <CronIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "cron generator",
      "cron expression editor",
      "crontab generator",
      "schedule cron job",
      "cron syntax helper",
      "linux cron scheduler",
    ],
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description: "Convert text into SEO-friendly URL slugs.",
    seoTitle: "URL Slug Generator | SEO Friendly URL Converter",
    seoDescription:
      "Instantly create clean, SEO-friendly URL slugs from any text. Remove special characters and optimize your links for better search ranking. Free and private.",
    icon: <Link2Icon />,
    category: ToolCategory.TEXT,
    keywords: [
      "slug generator",
      "url slug creator",
      "seo url builder",
      "text to slug",
      "create clean url",
      "hyphenate text",
    ],
  },
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate SEO meta tags for your website.",
    seoTitle: "Meta Tag Generator | Free SEO Meta Tags Builder",
    seoDescription:
      "Generate perfect SEO meta tags for your website in seconds. Create title, description, keywords, and Open Graph tags to boost your search rankings.",
    icon: <TagIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "meta tag generator",
      "seo meta tags",
      "open graph generator",
      "meta description builder",
      "social media meta tags",
      "html meta tag builder",
    ],
  },
  {
    id: "contrast-checker",
    name: "Contrast Checker",
    description: "Check color contrast accessibility (WCAG).",
    icon: <ContrastIcon />,
    category: ToolCategory.COLOR,
  },
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Visual calculator for Unix file permissions.",
    seoTitle: "Chmod Calculator | Unix File Permissions generator",
    seoDescription:
      "Calculate numeric (octal) and symbolic (rwx) file permissions for Unix/Linux systems. Visual Chmod Calculator makes setting permissions safe and easy.",
    icon: <ChmodIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "chmod calculator",
      "linux permissions calculator",
      "chmod generator",
      "unix file permissions",
      "octal permissions tool",
      "chmod 777 explanation",
    ],
  },
  {
    id: "utm-builder",
    name: "UTM Builder",
    description: "Build tracking URLs for marketing campaigns.",
    icon: <UtmIcon />,
    category: ToolCategory.PRODUCTIVITY,
  },
  {
    id: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    description: "Calculate dimensions and aspect ratios for images and video.",
    seoTitle: "Aspect Ratio Calculator | Resize Images & Video",
    seoDescription:
      "Calculate aspect ratios and dimensions for images and videos instantly. Essential tool for designers and video editors to find precise width and height.",
    icon: <AspectRatioIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "aspect ratio calculator",
      "image dimension calculator",
      "16:9 calculator",
      "resize calculator",
      "video aspect ratio tool",
      "calculate height from width",
    ],
  },
  {
    id: "css-triangle-generator",
    name: "CSS Triangle Generator",
    description: "Generate CSS code for geometric triangles.",
    icon: <TriangleIcon />,
    category: ToolCategory.CSS,
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Beautify and format XML strings.",
    seoTitle: "Online XML Formatter | Validate & Beautify XML",
    seoDescription:
      "Format, validate, and beautify your XML data instantly. Our free online XML Formatter makes XML readable and easier to debug. 100% private.",
    icon: <XmlIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "xml formatter",
      "xml beautifier",
      "format xml online",
      "xml prettifier",
      "xml validator",
      "xml syntax highlight",
    ],
  },
  {
    id: "morse-converter",
    name: "Morse Code Converter",
    description: "Translate text to Morse code and vice versa.",
    icon: <MorseIcon />,
    category: ToolCategory.FUN,
  },
  {
    id: "binary-converter",
    name: "Binary Converter",
    description: "Translate text to binary code and back.",
    icon: <BinaryIcon />,
    category: ToolCategory.CODING,
  },
  {
    id: "password-strength",
    name: "Password Strength Checker",
    description: "Test the strength of your passwords.",
    icon: <ShieldCheckIcon />,
    category: ToolCategory.MISC,
  },
  {
    id: "string-escaper",
    name: "String Escaper",
    description: "Escape strings for JSON, HTML, URL, and Java.",
    seoTitle: "String Escaper | Escape JSON, HTML, and URL Strings",
    seoDescription:
      "Quickly escape special characters for JSON, HTML, URLs, Java, and JavaScript. Prevent syntax errors and security issues with our free String Escaper.",
    icon: <StringEscaperIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "string escaper",
      "json escape tool",
      "html escape string",
      "url escape characters",
      "java string escaper",
      "escape special characters",
    ],
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Quickly calculate percentages for common math problems.",
    icon: <PercentIcon />,
    category: ToolCategory.MATH,
  },
  {
    id: "markdown-table-generator",
    name: "Markdown Table Generator",
    description: "Create Markdown tables easily with a visual editor.",
    seoTitle: "Markdown Table Generator | Visual Markdown Table Editor",
    seoDescription:
      "Easily create and format Markdown tables with our free visual editor. Convert CSV or Excel data to Markdown instantly. Perfect for READMEs and documentation.",
    icon: <TableIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      "markdown table generator",
      "convert csv to markdown",
      "excel to markdown table",
      "visual markdown editor",
      "table to markdown",
      "generate md table",
    ],
  },
  {
    id: "list-randomizer",
    name: "List Randomizer",
    description: "Shuffle and randomize a list of items.",
    icon: <ListIcon />,
    category: ToolCategory.FUN,
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    description: "Remove extra spaces, line breaks, and format text.",
    seoTitle: "Text Cleaner Tool | Remove Spaces, Breaks & Formatting",
    seoDescription:
      "Clean and format your text instantly. Remove extra spaces, line breaks, HTML tags, and more with our free online Text Cleaner. Perfect for writers and developers.",
    icon: <EraserIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      "text cleaner online",
      "remove line breaks",
      "remove extra spaces",
      "clean text formatting",
      "strip html tags",
      "normalize text",
    ],
  },

  {
    id: "svg-to-data-uri",
    name: "SVG to Data URI",
    description: "Convert SVG code into a Data URI for use in CSS.",
    seoTitle: "SVG to Data URI Converter | Encode SVG for CSS",
    seoDescription:
      "Convert SVG code into a base64 Data URI instantly. Optimize your web performance by embedding SVGs directly into CSS or HTML.",
    icon: <ImageIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "svg to data uri",
      "svg encoder",
      "svg to base64",
      "embed svg in css",
      "svg data url generator",
      "optimize svg for web",
    ],
  },
  {
    id: "json-yaml-converter",
    name: "JSON <> YAML Converter",
    description: "Convert between JSON and YAML.",
    seoTitle: "JSON <> YAML Converter | Bidirectional Conversion",
    seoDescription:
      "Convert JSON to YAML and YAML to JSON instantly. Our free online tool ensures accurate conversion for configuration files and data structures.",
    icon: <FileCodeIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "json to yaml",
      "yaml to json",
      "convert json to yaml",
      "convert yaml to json",
      "yaml converter",
      "json converter",
    ],
  },
  // Batch 3
  {
    id: "youtube-thumbnail",
    name: "YouTube Thumbnail Downloader",
    description:
      "Download thumbnails from any YouTube video in max resolution.",
    seoTitle: "YouTube Thumbnail Downloader | Save HD Thumbnails",
    seoDescription:
      "Download high-quality thumbnails from any YouTube video. Get Max Res, HD, SD, and default sizes instantly. fast, free, and easy to use.",
    icon: <YoutubeIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "youtube thumbnail downloader",
      "save youtube thumbnail",
      "download video cover",
      "get youtube thumbnail image",
      "hd thumbnail grabber",
      "youtube image extractor",
    ],
  },
  {
    id: "fancy-font-generator",
    name: "Fancy Font Generator",
    description: "Generate stylish text for social media bios.",
    seoTitle: "Fancy Font Generator | Stylish Text for Instagram & Bio",
    seoDescription:
      "Generate cool, fancy text styles for your Instagram bio, Twitter, and other social media. Copy and paste stylish fonts with our free online generator.",
    icon: <PenIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      "fancy font generator",
      "instagram font generator",
      "cool text generator",
      "stylish text maker",
      "aesthetic font copy paste",
      "bio font changer",
    ],
  },
  {
    id: "hashtag-extractor",
    name: "Hashtag Extractor",
    description: "Extract hashtags from a block of text.",
    seoTitle: "Hashtag Extractor | Find Hashtags in Text Instantly",
    seoDescription:
      "Instantly extract all hashtags from any text block. Perfect for social media managers and marketers to analyze and collect tags from posts.",
    icon: <TagsIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      "hashtag extractor",
      "find hashtags in text",
      "extract tags from instagram",
      "hashtag finder tool",
      "social media tag extractor",
      "grab hashtags",
    ],
  },
  {
    id: "image-filters",
    name: "Instagram Photo Filters",
    description: "Apply CSS filters like grayscale, sepia, and blur to images.",
    seoTitle: "Online Image Filters | Apply Instagram-like Effects",
    seoDescription:
      "Enhance your photos with free online filters. Apply Grayscale, Sepia, Blur, Brightness, and more instantly directly in your browser.",
    icon: <FiltersIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "online photo filters",
      "css image filters",
      "instagram filters online",
      "image effects tool",
      "grayscale converter",
      "photo editor online",
    ],
  },
  {
    id: "svg-blob-generator",
    name: "SVG Blob Generator",
    description: "Create organic blob shapes for backgrounds.",
    seoTitle: "SVG Blob Generator | Create Organic Shapes",
    seoDescription:
      "Generate unique, organic SVG blobs for your web design backgrounds. Customize complexity and contrast to create the perfect shape. Free and open-source.",
    icon: <BlobIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "svg blob generator",
      "organic shape generator",
      "blob maker",
      "svg background shapes",
      "web design blobs",
      "random blob creator",
    ],
  },
  {
    id: "svg-wave-generator",
    name: "SVG Wave Generator",
    description: "Generate smooth wave dividers for your website.",
    seoTitle: "SVG Wave Generator | Create Website Section Dividers",
    seoDescription:
      "Create beautiful SVG waves for your website headers and footers. Customize layers, height, and color to generate the perfect wave divider.",
    icon: <WavesIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "svg wave generator",
      "website divider generator",
      "css wave shape",
      "svg path generator",
      "wave background maker",
      "section separator",
    ],
  },
  {
    id: "keycode-info",
    name: "Keycode Event Info",
    description: "Get JavaScript event codes for any key press.",
    seoTitle: "Keycode Info | JavaScript Key Events & Codes",
    seoDescription:
      "Press any key to get its JavaScript KeyCode, code, key, and other event properties. Essential tool for web developers handling keyboard events.",
    icon: <KeyboardIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "javascript keycode",
      "keyboard event viewer",
      "key code checker",
      "js keyboard events",
      "find key code",
      "keyboard test",
    ],
  },
  {
    id: "screen-info",
    name: "Screen Resolution Info",
    description: "View your current screen and viewport dimensions.",
    icon: <ScreenIcon />,
    category: ToolCategory.PRODUCTIVITY,
  },
  {
    id: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text to spoken audio in your browser.",
    seoTitle: "Text to Speech Converter | Free Online TTS",
    seoDescription:
      "Convert any text to lifelike speech instantly. Choose from multiple voices and languages with our free, browser-based Text to Speech (TTS) tool.",
    icon: <MicIcon />,
    category: ToolCategory.FUN,
    keywords: [
      "text to speech online",
      "free tts tool",
      "convert text to audio",
      "read text aloud",
      "browser tts",
      "speech synthesis",
    ],
  },
  {
    id: "roman-numeral-converter",
    name: "Roman Numeral Converter",
    description: "Convert numbers to Roman numerals and back.",
    icon: <RomanIcon />,
    category: ToolCategory.MATH,
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age in years, months, and days.",
    icon: <BabyIcon />,
    category: ToolCategory.MATH,
  },
  {
    id: "random-number-generator",
    name: "Random Number Generator",
    description: "Generate random numbers within a specific range.",
    icon: <DiceIcon />,
    category: ToolCategory.MATH,
  },
  {
    id: "duplicate-remover",
    name: "Duplicate Line Remover",
    description: "Remove duplicate entries from a list of text.",
    seoTitle: "Duplicate Line Remover | Remove Duplicate Lines Online",
    seoDescription:
      "Instantly remove duplicate lines from your text list. Clean up data, emails, or inventory lists with our free, secure duplicate remover tool.",
    icon: <DuplicateIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      "duplicate remover",
      "remove duplicate lines",
      "deduplicate text",
      "list cleaner",
      "delete duplicates online",
      "unique line filter",
    ],
  },
  {
    id: "html-entity",
    name: "HTML Entity Encoder",
    description: "Encode/Decode text to HTML entities.",
    seoTitle: "HTML Entity Encoder/Decoder | Escape HTML Characters",
    seoDescription:
      "Convert text to HTML entities and back. Safely escape special characters like <, >, and & for use in web pages. Free, fast, and secure.",
    icon: <HtmlEntityIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "html entity encoder",
      "html decode",
      "escape html characters",
      "html special characters",
      "convert to html entities",
      "xml entity encoder",
    ],
  },
  {
    id: "css-cursors",
    name: "CSS Cursor Viewer",
    description: "Visual reference for all CSS cursor types.",
    icon: <CursorIcon />,
    category: ToolCategory.CSS,
  },
  {
    id: "device-resolutions",
    name: "Device Resolution List",
    description: "Reference guide for common device screen sizes.",
    icon: <DevicesIcon />,
    category: ToolCategory.PRODUCTIVITY,
  },
  {
    id: "lorem-image-generator",
    name: "Lorem Picsum Generator",
    description: "Generate placeholder image URLs.",
    seoTitle: "Lorem Picsum Generator | Random Placeholder Images",
    seoDescription:
      "Generate random, high-quality placeholder images for your web designs. Get customizable URLs for specific sizes and effects (grayscale, blur).",
    icon: <PlaceholderIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "placeholder image generator",
      "lorem picsum tool",
      "random image url",
      "dummy image generator",
      "web design placeholders",
      "mockup images",
    ],
  },
  {
    id: "css-borders",
    name: "CSS Border Preview",
    description: "Visualizer for all CSS border styles.",
    icon: <BorderIcon />,
    category: ToolCategory.CSS,
  },
  {
    id: "css-patterns",
    name: "CSS Background Patterns",
    description: "Generate pure CSS background patterns.",
    icon: <PatternIcon />,
    category: ToolCategory.CSS,
  },
  {
    id: "signature-pad",
    name: "Signature Pad",
    description: "Draw and save digital signatures.",
    icon: <SignatureIcon />,
    category: ToolCategory.MISC,
  },
  // ... rest of the existing tools (ensure Readability Score, Loan Calculator, etc. are preserved)
  {
    id: "readability-score-calculator",
    name: "Readability Score Calculator",
    description:
      "Analyze text complexity and calculate Flesch-Kincaid and other readability scores to improve content clarity and accessibility.",
    seoTitle:
      "Free Readability Score Calculator | Instantly Check Your Content's Grade Level",
    seoDescription:
      "Is your writing easy to understand? Our free Readability Score Calculator gives you instant feedback with Flesch-Kincaid scores. Write clearer, more effective content for everyone. 100% private.",
    icon: <ReadabilityIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      "readability score calculator",
      "flesch kincaid readability",
      "readability checker online",
      "text grade level checker",
      "content readability tool",
      "reading ease score",
      "writing clarity analyzer",
      "text complexity checker",
      "writing score",
      "content accessibility",
    ],

  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    description:
      "Calculate accurate monthly payments, interest costs, and a complete amortization schedule for any type of loan.",
    seoTitle: "Free Loan Calculator | Estimate Monthly Payments & Amortization",
    seoDescription:
      "Take control of your finances. Our free Loan Calculator helps you estimate monthly payments, total interest, and see a full amortization schedule for any loan. Plan for mortgages, car loans, and more. Fast, accurate, and 100% private.",

    icon: <LoanCalculatorIcon />,
    category: ToolCategory.MATH,

    keywords: [
      "loan calculator",
      "monthly payment calculator",
      "loan amortization calculator",
      "mortgage payment calculator",
      "car loan calculator",
      "interest rate calculator",
      "principal and interest calculator",
      "loan repayment schedule",
      "financial planning tool",
    ],

  },
  {
    id: "timezone-converter",
    name: "Time Zone Converter",
    description:
      "Instantly convert any date and time between global time zones with precise, real-time accuracy.",
    seoTitle:
      "Time Zone Converter | Instantly Convert Time Between Cities Worldwide",
    seoDescription:
      "Never get the time wrong again. Our free Time Zone Converter makes it easy to convert time between any cities in the world. Perfect for scheduling meetings, planning travel, and staying in sync with global teams.",
    icon: <TimeZoneConverterIcon />,
    category: ToolCategory.PRODUCTIVITY,

    keywords: [
      "time zone converter",
      "timezone calculator",
      "world time converter",
      "time difference calculator",
      "international meeting scheduler",
      "gmt to ist converter",
      "pst to est converter",
      "utc time converter",
      "global clock",
      "remove duplicates",
      "text cleaner",
    ],

  },
  {
    id: "comma-separator",
    name: "Comma Separator",
    description: "Convert lists to comma-separated text with advanced formatting.",
    seoTitle: "Comma Separator | Convert Column to Comma Separated List",
    seoDescription:
      "Free online tool to convert lists to comma-separated values (CSV) and vice versa. Support for custom delimiters, wrapping, sorting, and duplicate removal.",
    icon: <SeparatorIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      "comma separator",
      "column to comma",
      "list to csv",
      "delimiter converter",
      "text joiner",
      "split text",
      "delim.co alternative",
    ],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description:
      "Convert text between uppercase, lowercase, title case, and more formats.",
    seoTitle: "Online Case Converter | Instantly Change Text Case",
    seoDescription:
      "Quickly convert text to UPPERCASE, lowercase, Title Case, Sentence case, and more with our free online tool. Perfect for headlines, essays, and code. 100% private and easy to use.",
    icon: <CaseIcon />,
    category: ToolCategory.TEXT,
    featured: true,
    keywords: [
      "text case converter",
      "change case online",
      "uppercase to lowercase",
      "title case generator",
      "sentence case tool",
      "text formatting",
    ],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description:
      "Instantly count words, characters, sentences, and paragraphs with our advanced, real-time Word Counter tool.",
    seoTitle: "Free Online Word Counter | Real-Time Word & Character Count",
    seoDescription:
      "Hit your writing goals with our free online Word Counter. Get instant, accurate counts for words, characters, sentences, and paragraphs, plus an estimated reading time. Perfect for writers, students, and SEOs.",
    icon: <WordCounterIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      "word counter",
      "word count tool",
      "character counter",
      "online word counter",
      "word calculator",
      "sentence counter",
      "paragraph counter",
      "text analysis tool",
      "reading time calculator",
      "content writing tool",
    ],
  },
  {
    id: "character-counter",
    name: "Character Counter",
    description:
      "Count characters, letters, and byte size instantly to ensure your text fits limits for social media, SMS, and online platforms.",
    seoTitle: "Online Character Counter | Letter, Symbol & Byte Counter",
    seoDescription:
      "Never exceed the limit again. Our free Character Counter instantly checks characters, letters, and byte size. Perfect for Twitter/X posts, SMS, and more. 100% private and secure.",
    icon: <CharacterCounterIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      "character counter online",
      "letter count tool",
      "byte size calculator",
      "text character limit",
      "social media post counter",
      "SMS character counter",
      "Unicode character counter",
      "emoji byte counter",
    ],

  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description:
      "Generate customizable placeholder text for web design, UI/UX prototypes, print layouts, and content mockups.",
    seoTitle: "Lorem Ipsum Generator | Create Custom Placeholder Text",
    seoDescription:
      "Need placeholder text? Our free Lorem Ipsum Generator creates custom dummy text for your designs. Generate paragraphs, sentences, or words to perfect your layouts. Fast, easy, and professional.",
    icon: <LoremIpsumIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      "lorem ipsum generator",
      "placeholder text generator",
      "dummy text creator",
      "mockup text tool",
      "filler text generator",
      "UI/UX placeholder text",
      "web design dummy text",
      "design content filler",
    ],

  },
  {
    id: "text-reverser",
    name: "Text Reverser",
    description:
      "Instantly reverse any string of text, words, letters, or symbols for fun, puzzles, or programming tasks.",
    seoTitle: "Online Text Reverser | Reverse Words, Letters & Strings",
    seoDescription:
      "Flip your text backwards with our free Text Reverser. Instantly reverse words, letters, and even emojis. Perfect for fun social media posts, puzzles, or coding challenges.",
    icon: <TextReverseIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      "text reverser online",
      "reverse words tool",
      "string reverser",
      "backwards text generator",
      "mirror text creator",
      "flip letters online",
      "reverse string tool",
      "unicode text reverser",
    ],

  },
  {
    id: "markdown-previewer",
    name: "Markdown Previewer",
    description:
      "Write Markdown and instantly see the rendered HTML in a live, real-time preview for documentation, blogs, and READMEs.",
    seoTitle: "Live Markdown Editor | Real-Time Markdown Previewer",
    seoDescription:
      "Write and preview Markdown side-by-side with our free live editor. Instantly see how your text will look as HTML. Perfect for READMEs, blogs, and documentation. Fast, secure, and easy to use.",
    icon: <MarkdownIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      "markdown editor online",
      "live markdown preview",
      "markdown to html converter",
      "readme editor",
      "md file viewer",
      "markdown live editor",
      "markdown documentation tool",
      "markdown blog preview",
    ],

  },
  // Coding Tools
  {
    id: "base64-converter",
    name: "Base64 Converter",
    description:
      "Instantly encode and decode text, images, and files to/from Base64 online.",
    seoTitle: "Online Base64 Converter | Encode & Decode Text, Files & Images",
    seoDescription:
      "A free, powerful tool to encode and decode Base64. Easily convert text, images, or any file into a Base64 string and back again. Secure, fast, and all in your browser.",
    icon: <Base64Icon />,
    category: ToolCategory.CODING,
    keywords: [
      "base64 converter online",
      "encode text to base64",
      "decode base64 string",
      "file to base64 converter",
      "data uri generator online",
      "base64 image",
    ],
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode strings for safe URL transmission online.",
    seoTitle: "Online URL Encoder & Decoder | Percent-Encoding Tool",
    seoDescription:
      "Quickly and safely encode or decode strings for use in URLs. Our free tool handles special characters and spaces, preventing broken links. Perfect for developers and marketers.",
    icon: <UrlIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "url encoder decoder online",
      "percent encoding tool",
      "url safe encoding",
      "encodeURIComponent online",
      "query string encoder",
      "url escape tool",
    ],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description:
      "Validate, format, and pretty-print your JSON data instantly online.",
    seoTitle: "Online JSON Formatter | Validate & Beautify JSON",
    seoDescription:
      "Clean up your messy JSON with our free online formatter. Instantly validate, format, and beautify your JSON data to make it readable. Perfect for developers debugging APIs.",
    icon: <JsonIcon />,
    category: ToolCategory.CODING,
    featured: true,
    keywords: [
      "json formatter online",
      "json validator",
      "pretty print json online",
      "json beautifier tool",
      "json viewer online",
      "json lint",
    ],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug regular expressions against strings online.",
    seoTitle: "Online Regex Tester | Test & Debug Regular Expressions",
    seoDescription:
      "Test your regular expressions in real-time with our free online Regex Tester. Instantly see matches and capture groups highlighted. Perfect for developers and data analysts. 100% private.",
    icon: <RegexIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "regex tester online",
      "regular expression tester",
      "javascript regex checker",
      "validate regex pattern",
      "regex debugger online",
      "regex live test",
    ],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate secure, random UUIDs (v4) online instantly.",
    seoTitle: "Online UUID Generator | Instantly Create Random UUIDs (v4)",
    seoDescription:
      "Need a unique ID? Our free UUID Generator creates random, secure Version 4 UUIDs in a single click. Perfect for databases, session IDs, and any application needing a unique identifier.",
    icon: <UuidIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "uuid generator online",
      "generate uuid v4",
      "random uuid online",
      "guid generator",
      "unique identifier generator",
      "crypto.randomuuid",
    ],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description:
      "Create SHA-1, SHA-256, or SHA-512 hashes online from any text.",
    seoTitle:
      "Online Hash Generator | Generate SHA-1, SHA-256 & SHA-512 Hashes",
    seoDescription:
      "Instantly generate secure SHA-1, SHA-256, and SHA-512 hashes from any text with our free online tool. Powered by the Web Crypto API for maximum security. 100% private.",
    icon: <HashIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "sha256 generator online",
      "sha512 hash calculator",
      "sha1 generator online",
      "string to hash",
      "web crypto hash tool",
      "text to sha256",
    ],
  },
  {
    id: "jwt-debugger",
    name: "JWT Decoder",
    description: "Decode JSON Web Tokens to view header and payload online.",
    seoTitle: "Online JWT Decoder | Decode & Inspect JSON Web Tokens",
    seoDescription:
      "Instantly decode and inspect JSON Web Tokens (JWTs) with our free online tool. View the header and payload in a readable format. Perfect for debugging authentication tokens. 100% private.",
    icon: <JwtIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "jwt decoder online",
      "json web token decoder",
      "inspect jwt payload",
      "decode jwt online",
      "auth token debugger",
      "jwt.io alternative",
    ],
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description:
      "Instantly compare text or code and highlight every difference in seconds.",
    seoTitle: "Online Diff Checker | Instantly Compare Text & Code",
    seoDescription:
      "Easily compare two blocks of text or code and see the differences highlighted instantly. Our free Diff Checker is perfect for developers, writers, and editors. Fast, secure, and 100% private.",
    icon: <DiffIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "diff tool online",
      "compare text",
      "compare code",
      "track changes",
      "highlight differences",
      "text comparison tool",
    ],
  },
  {
    id: "json-csv-converter",
    name: "JSON <> CSV Converter",
    description:
      "Convert between JSON and CSV formats instantly.",
    seoTitle: "Online JSON <> CSV Converter | Free & Instant",
    seoDescription:
      "Effortlessly convert between JSON and CSV formats with our free online tool. Perfect for developers and data analysts. Fast, secure, and browser-based.",
    icon: <CsvToJsonIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "csv to json online",
      "json to csv online",
      "convert csv to json",
      "convert json to csv",
      "csv parser",
      "data transformation tool",
    ],
  },
  {
    id: "csv-xlsx-converter",
    name: "Data Converter",
    description:
      "The ultimate data conversion tool. Convert CSV or XLSX files to JSON, SQL, HTML, and more, instantly in your browser.",
    seoTitle:
      "Universal Data Converter | Convert CSV, XLSX, JSON, SQL, and more",
    seoDescription:
      "Our free online Data Converter instantly transforms your files. Convert CSV or Excel (XLSX) to JSON, SQL, HTML, Markdown, and more. Secure, browser-based, and incredibly fast.",
    icon: <FileConversionIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "data converter",
      "file converter",
      "csv to json",
      "xlsx to csv",
      "csv to sql",
      "excel to json",
      "json to csv",
      "data transformation",
      "file format converter",
      "browser-based tools",
    ],
  },
  // Image Tools
  {
    id: "image-to-base64",
    name: "Image to Base64",
    description: "Convert an image file into a Base64 data URL string.",
    seoTitle: "Image to Base64 Converter | Instantly Encode Images Online",
    seoDescription:
      "Convert any image (PNG, JPG, SVG) into a Base64 data URL with our free online tool. Perfect for embedding images directly into HTML and CSS to improve site speed. 100% private.",
    icon: <ImageIcon />,
    category: ToolCategory.IMAGE,
    featured: true,
    keywords: [
      "image to base64 converter",
      "data uri generator",
      "embed image in html",
      "css background image base64",
      "png to base64",
      "jpg to base64",
    ],
  },
  {
    id: "base64-to-image",
    name: "Base64 to Image",
    description: "Convert a Base64 data URL into a viewable image.",
    seoTitle: "Base64 to Image Converter | Decode & View Base64 Images",
    seoDescription:
      "Have a Base64 string and want to see the image? Our free tool instantly decodes any Base64 data URL back into a viewable and downloadable image. Perfect for developers and designers.",
    icon: <Base64ToImageIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "base64 to image converter",
      "decode base64 to image",
      "view base64 image",
      "data uri viewer",
      "base64 image downloader",
    ],
  },
  // CSS Tools
  {
    id: "box-shadow-generator",
    name: "Box Shadow Generator",
    description:
      "Create and customize CSS box-shadow effects with a visual editor.",
    seoTitle: "CSS Box Shadow Generator | Visual & Interactive Tool",
    seoDescription:
      "Design the perfect CSS box-shadow with our free visual generator. Control offsets, blur, spread, and color in real-time and get the code instantly. Perfect for modern UI design.",
    icon: <BoxShadowIcon />,
    category: ToolCategory.CSS,
    keywords: [
      "css box shadow generator",
      "visual box shadow tool",
      "css shadow creator",
      "drop shadow css",
      "inset shadow generator",
      "css ui generator",
    ],
  },
  {
    id: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description:
      "Create beautiful CSS gradients with color pickers and angle controls.",
    seoTitle: "CSS Gradient Generator | Create Beautiful Gradients Online",
    seoDescription:
      "Design stunning linear and radial CSS gradients with our free visual editor. Add multiple colors, control angles, and get production-ready code instantly. Perfect for modern web design.",
    icon: <GradientIcon />,
    category: ToolCategory.CSS,
    keywords: [
      "css gradient generator",
      "gradient generator online",
      "css gradient background generator",
      "linear gradient css generator",
      "radial gradient css generator",
      "conic gradient generator",
      "css gradient code generator",
      "gradient background maker for website",
      "css gradient editor live preview",
      "animated css gradient generator",
      "gradient button generator css",
      "css gradient tutorial for beginners",
      "generate css gradient code free",
      "multi color css gradient generator",
      "best css gradient generator 2025",
      "how to make css gradient background",
      "css gradient maker with angle control",
      "css gradient presets for UI design",
      "copy css gradient code",
      "css gradient generator for tailwind",
    ],
  },
  {
    id: "border-radius-generator",
    name: "Border Radius Generator",
    description:
      "Create custom border radius values with individual corner controls.",
    seoTitle: "CSS Border Radius Generator | Create Custom Shapes",
    seoDescription:
      "Visually design the perfect rounded corners with our free CSS Border Radius Generator. Control each corner individually to create unique shapes and get the code instantly.",
    icon: <BorderRadiusIcon />,
    category: ToolCategory.CSS,
    keywords: [
      "css border radius generator",
      "rounded corners css",
      "custom shape css",
      "visual border radius tool",
      "css shape generator",
    ],
  },
  {
    id: "text-shadow-generator",
    name: "Text Shadow Generator",
    description:
      "Create beautiful text shadows with precise control over position and blur.",
    seoTitle: "CSS Text Shadow Generator | Visual & Interactive Tool",
    seoDescription:
      "Design the perfect CSS text-shadow with our free visual generator. Control offsets, blur, color, and opacity in real-time and get the code instantly. Add depth and style to your text.",
    icon: <TextShadowIcon />,
    category: ToolCategory.CSS,
    keywords: [
      "css text shadow generator",
      "text glow effect css",
      "3d text css",
      "visual text shadow tool",
      "font shadow",
    ],
  },
  {
    id: "glassmorphism-generator",
    name: "Glassmorphism & Neumorphism Generator",
    description:
      "Create modern glassmorphism and neumorphism effects with visual controls.",
    seoTitle: "Glassmorphism & Neumorphism CSS Generator | Modern UI Tool",
    seoDescription:
      "Easily create trendy Glassmorphism (frosted glass) and Neumorphism (soft UI) effects with our free visual CSS generator. Get the code for your modern UI designs instantly.",
    icon: <GlassmorphismIcon />,
    category: ToolCategory.CSS,
    keywords: [
      "glassmorphism css generator",
      "frosted glass effect css",
      "neumorphism ui generator",
      "css blur background",
      "modern ui design",
      "soft ui css",
    ],
  },
  // Color Tools
  {
    id: "color-palette-generator",
    name: "Color Palette Generator",
    description: "Generate color palettes from a base color.",
    seoTitle: "Color Palette Generator | Create Beautiful Color Schemes",
    seoDescription:
      "Instantly generate beautiful, harmonious color palettes from any base color. Our free tool creates monochromatic, analogous, complementary, and triadic schemes for your designs.",
    icon: <PaletteIcon />,
    category: ToolCategory.COLOR,
    keywords: [
      "color palette generator",
      "color scheme generator",
      "design color combinations",
      "monochromatic color palette",
      "complementary colors",
      "color wheel tool",
    ],
  },
  {
    id: "color-theme-wheel",
    name: "Color Theme Generator (Color Wheel)",
    description:
      "Generate color themes using an interactive color wheel and scheme presets (analogous, complementary, triad, etc.).",
    seoTitle: "Interactive Color Wheel | Color Theme Generator",
    seoDescription:
      "Design beautiful color themes with our free interactive color wheel. Choose from analogous, complementary, and triadic schemes and export your palette as CSS variables or JSON.",
    icon: <PaletteIcon />,
    category: ToolCategory.COLOR,
    keywords: [
      "color wheel tool",
      "color harmony generator",
      "triadic color scheme",
      "analogous colors",
      "color picker online",
      "ui color palette generator",
    ],
  },
  {
    id: "css-color-code-converter",
    name: "CSS Color Code Converter",
    description:
      "Convert between HEX/HEXA, RGB/RGBA, HSL/HSLA, and CSS color keywords.",
    seoTitle: "CSS Color Code Converter | HEX, RGB & HSL Converter",
    seoDescription:
      "Instantly convert between HEX, RGB, and HSL color codes with our free online tool. Supports alpha channels (transparency) and CSS color names. Perfect for developers and designers.",
    icon: <ColorIcon />,
    category: ToolCategory.COLOR,
    keywords: [
      "hex to rgb converter",
      "hsl to hex",
      "rgba color picker",
      "css color converter",
      "color code translator",
      "hex to hsl",
    ],
  },
  {
    id: "video-compressor",
    name: "Video Compressor",
    description: "Reduce video file size without significant quality loss.",
    seoTitle: "Online Video Compressor | Reduce Video File Size Free",
    seoDescription:
      "Compress MP4, MOV, and AVI video files online for free. Reduce file size without losing quality. Perfect for sharing on WhatsApp, Email, or Web.",
    icon: <VideoCompressorIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      "video compressor online",
      "reduce video size",
      "compress mp4",
      "video size reducer",
      "shrink video file",
      "free video compression",
    ],
  },
  {
    id: "video-to-audio-converter",
    name: "Video to Audio Converter",
    description: "Extract audio tracks from video files as MP3.",
    seoTitle: "Video to Audio Converter | Extract MP3 from MP4",
    seoDescription:
      "Extract audio from any video file instantly. Convert MP4 to MP3, WAV, or AAC with our free online Video to Audio Converter.",
    icon: <VideoToAudioIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      "video to audio",
      "convert mp4 to mp3",
      "extract audio from video",
      "video to sound converter",
      "mp4 to audio",
      "online audio extractor",
    ],
  },
  {
    id: "gif-maker",
    name: "GIF Maker",
    description: "Convert video clips into animated GIFs.",
    seoTitle: "Online GIF Maker | Create Animated GIFs from Video",
    seoDescription:
      "Create funny animated GIFs from your videos instantly. Convert MP4 to GIF with customizable start/end times and dimensions.",
    icon: <GifMakerIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      "gif maker online",
      "video to gif",
      "create gif from video",
      "mp4 to gif",
      "make animated gif",
      "free gif generator",
    ],
  },
  {
    id: "trim-video",
    name: "Trim Video",
    description: "Cut and trim video files to desired length.",
    seoTitle: "Online Video Trimmer | Cut & Trim MP4 Videos",
    seoDescription:
      "Trim and cut your video files online for free. Remove unwanted parts from the beginning, middle, or end of your videos easily.",
    icon: <TrimVideoIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      "trim video online",
      "video cutter",
      "cut mp4 video",
      "online video splitter",
      "video clipper",
      "free video trimmer",
    ],
  },
  {
    id: "format-converter",
    name: "Video Format Converter",
    description: "Convert videos between different formats like MP4, AVI, MOV.",
    seoTitle: "Video Format Converter | Change Video Format Online",
    seoDescription:
      "Convert video files to any format (MP4, AVI, MKV, MOV, WEBM) for free. Fast, secure, and high-quality online video converter.",
    icon: <FormatConverterIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      "video format converter",
      "convert mp4 to avi",
      "mov to mp4",
      "change video format",
      "online video transcoder",
      "free video converter",
    ],
  },
  {
    id: "video-thumbnail-extractor",
    name: "Video Thumbnail Extractor",
    description: "Extract image thumbnails from specific timestamps in a video.",
    seoTitle: "Video Thumbnail Extractor | Capture Frames from Video",
    seoDescription:
      "Extract high-quality image frames from any video. Pick a timestamp and save the frame as JPG or PNG for thumbnails.",
    icon: <VideoThumbnailIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      "video thumbnail extractor",
      "capture frame from video",
      "video screenshot tool",
      "get image from video",
      "video frame grabber",
      "create thumbnail from video",
    ],
  },
  {
    id: "video-mute",
    name: "Mute Video",
    description: "Remove audio track from a video file.",
    seoTitle: "Mute Video Online | Remove Sound from Video",
    seoDescription:
      "Instantly remove the audio track from any video. Mute background noise or create a silent video clips for social media.",
    icon: <VideoMuteIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      "mute video online",
      "remove audio from video",
      "silence video",
      "video mute tool",
      "delete sound from video",
      "mp4 muter",
    ],
  },
  {
    id: "watermark-adder",
    name: "Watermark Adder",
    description: "Add image or text watermarks to your photos.",
    seoTitle: "Watermark Adder | Add Logo & Text to Photos",
    seoDescription:
      "Protect your images with our free online Watermark Adder. Add text or logo watermarks to photos easily to prevent theft.",
    icon: <WatermarkAdderIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "add watermark online",
      "photo watermark tool",
      "add logo to photo",
      "image copyright protector",
      "free watermark app",
      "watermark images",
    ],
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images by dimensions or percentage.",
    seoTitle: "Image Resizer | Resize Photos Online Free",
    seoDescription:
      "Resize images online to any dimension or percentage. Change width and height of JPG, PNG, and WebP images without losing quality.",
    icon: <ImageResizerIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "image resizer",
      "resize photo online",
      "change image size",
      "picture resizer tool",
      "scale image",
      "resize jpg",
    ],
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert images between formats like PNG, JPG, WEBP.",
    seoTitle: "Image Converter | Convert JPG, PNG, WebP Online",
    seoDescription:
      "Convert images to any format (JPG, PNG, WebP) instantly. Free online image converter with bulk processing support.",
    icon: <ImageConverterIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "image converter online",
      "convert jpg to png",
      "webp converter",
      "change image format",
      "photo file converter",
      "bulk image converter",
    ],
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress images to reduce file size while maintaining quality.",
    seoTitle: "Image Compressor | Reduce Photo Size Online",
    seoDescription:
      "Compress JPG, PNG, and WebP images online. Reduce file size by up to 80% without visible quality loss. Speed up your website.",
    icon: <ImageCompressorIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "image compressor",
      "reduce image size",
      "compress jpg online",
      "optimize images for web",
      "photo size reducer",
      "compress png",
    ],
  },
  {
    id: "todo-list",
    name: "To-Do List",
    description: "A simple to-do list that saves your tasks in the browser.",
    seoTitle: "Simple To-Do List | Online & Persistent",
    seoDescription:
      "A clean and simple to-do list that saves your tasks in your browser. Organize your day and stay on track with our free and private To-Do List tool.",
    icon: <TodoIcon />,
    category: ToolCategory.PRODUCTIVITY,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords.",
    seoTitle: "Strong Password Generator | Create Secure Passwords",
    seoDescription:
      "Create random, secure passwords with custom length and characters. Protect your accounts with strong, uncrackable passwords created instantly.",
    icon: <PasswordIcon />,
    category: ToolCategory.CODING,
    keywords: [
      "password generator",
      "secure password creator",
      "random password tool",
      "strong password maker",
      "online password generator",
      "security tool",
    ],
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs.",
    seoTitle: "QR Code Generator | Create Free QR Codes",
    seoDescription:
      "Create custom QR codes for URLs, text, Wi-Fi, and more. Download your high-quality QR code in PNG or SVG format instantly.",
    icon: <QrCodeIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      "qr code generator",
      "create qr code",
      "free qr maker",
      "url to qr code",
      "custom qr code generator",
      "qr code creator",
    ],
  },
  {
    id: "date-calculator",
    name: "Date Calculator",
    description: "Calculate the difference between two dates.",
    seoTitle: "Date Calculator | Days Between Dates",
    seoDescription:
      "Calculate the exact duration between two dates in years, months, weeks, and days. Perfect for event planning and scheduling.",
    icon: <DateCalcIcon />,
    category: ToolCategory.MATH,
    keywords: [
      "date calculator",
      "days between dates",
      "date difference calculator",
      "time duration calculator",
      "calendar calculator",
      "age between dates",
    ],
  },
  {
    id: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "A timer to help you focus using the Pomodoro Technique.",
    seoTitle: "Pomodoro Timer Online | Focus & Productivity Timer",
    seoDescription:
      "Boost your productivity with our free online Pomodoro Timer. Use the 25-minute work / 5-minute break technique to stay focused and get more done.",
    icon: <PomodoroIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      "pomodoro timer",
      "tomato timer",
      "focus timer",
      "productivity timer",
      "pomodoro technique clock",
      "online study timer",
    ],
  },
  {
    id: "meme-generator",
    name: "Meme Generator",
    description: "Create your own memes with popular templates.",
    seoTitle: "Online Meme Generator | Create Funny Memes",
    seoDescription:
      "Make your own memes with our free online Meme Generator. Upload your images or caption popular templates. fast, funny, and no watermark.",
    icon: <MemeIcon />,
    category: ToolCategory.FUN,
    keywords: [
      "meme generator",
      "make a meme online",
      "meme creator",
      "funny meme maker",
      "caption images",
      "internet memes",
    ],
  },

  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert between different units of measurement.",
    seoTitle: "Unit Converter | Length, Weight, Temp & More",
    seoDescription:
      "Convert between thousands of units of measurement. Length, weight, temperature, volume, and more with our free online Unit Converter.",
    icon: <UnitConverterIcon />,
    category: ToolCategory.MATH,
    keywords: [
      "unit converter",
      "measurement converter",
      "convert units",
      "metric to imperial",
      "length converter",
      "weight conversion",
    ],
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index.",
    seoTitle: "BMI Calculator | Check Your Body Mass Index",
    seoDescription:
      "Calculate your Body Mass Index (BMI) instantly. Enter your height and weight to see if you are in a healthy weight range. Free and private.",
    icon: <BmiIcon />,
    category: ToolCategory.MATH,
    keywords: [
      "bmi calculator",
      "body mass index",
      "calculate bmi",
      "healthy weight calculator",
      "bmi chart",
      "weight checker",
    ],
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    description: "Convert between different currencies.",
    seoTitle: "Currency Converter | Real-Time Exchange Rates",
    seoDescription:
      "Convert between 190+ global currencies with live exchange rates. Fast, accurate, and free online Currency Converter.",
    icon: <CurrencyIcon />,
    category: ToolCategory.MATH,
    keywords: [
      "currency converter",
      "exchange rate calculator",
      "convert money",
      "usd to eur",
      "foreign exchange rates",
      "money converter",
    ],
  },
  {
    id: "world-clock",
    name: "World Clock",
    description: "Check the time in different cities around the world.",
    seoTitle: "World Clock | Current Time Across the Globe",
    seoDescription:
      "Check the current time in major cities around the world. Track multiple time zones instantly with our free World Clock tool.",
    icon: <WorldClockIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      "world clock",
      "current time world",
      "time zone clock",
      "global time",
      "world time zones",
      "meeting planner",
    ],
  },
  {
    id: "timers-and-stopwatch",
    name: "Timers and Stopwatch",
    description: "A simple timer and stopwatch.",
    seoTitle: "Online Timer & Stopwatch | Countup & Countdown",
    seoDescription:
      "A simple, full-screen online timer and stopwatch. Set alarms, countdowns, and track laps easily directly in your browser.",
    icon: <TimersIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      "online timer",
      "stopwatch online",
      "countdown timer",
      "alarm clock online",
      "lap timer",
      "web stopwatch",
    ],
  },
  {
    id: "keyword-density-analyzer",
    name: "Keyword Density Analyzer",
    description: "Analyze the keyword density of a text.",
    seoTitle: "Keyword Density Analyzer | SEO Content Checker",
    seoDescription:
      "Check the keyword density of your text to avoid stuffing and improve SEO. Analyze word frequency and optimize your content for search engines.",
    icon: <KeywordDensityIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      "keyword density checker",
      "word frequency counter",
      "seo content analyzer",
      "optimize keyword usage",
      "keyword stuffing checker",
      "text analysis tool",
    ],
  },
];

export const CATEGORY_ORDER: ToolCategory[] = [
  ToolCategory.TEXT,
  ToolCategory.IMAGE,
  ToolCategory.CSS,
  ToolCategory.CODING,
  ToolCategory.COLOR,
  ToolCategory.MATH,
  ToolCategory.PRODUCTIVITY,
  ToolCategory.FUN,
  ToolCategory.VIDEO,
  ToolCategory.MISC,
];

export const CATEGORY_URL_MAP: Record<ToolCategory, string> = {
  [ToolCategory.TEXT]: "text",
  [ToolCategory.IMAGE]: "image",
  [ToolCategory.CSS]: "css",
  [ToolCategory.CODING]: "coding",
  [ToolCategory.COLOR]: "color",
  [ToolCategory.MATH]: "calculator",
  [ToolCategory.PRODUCTIVITY]: "productivity",
  [ToolCategory.FUN]: "fun",
  [ToolCategory.VIDEO]: "video",
  [ToolCategory.MISC]: "other",
};

export const URL_TO_CATEGORY_MAP: Record<string, ToolCategory> = Object.entries(
  CATEGORY_URL_MAP
).reduce((acc, [key, value]) => {
  acc[value] = key as ToolCategory;
  return acc;
}, {} as Record<string, ToolCategory>);

export const CATEGORY_ICONS: Record<
  ToolCategory,
  React.ComponentType<{ className?: string }>
> = {
  [ToolCategory.TEXT]: TextCategoryIcon,
  [ToolCategory.IMAGE]: ImageCategoryIcon,
  [ToolCategory.CSS]: CssCategoryIcon,
  [ToolCategory.CODING]: CodeCategoryIcon,
  [ToolCategory.COLOR]: ColorCategoryIcon,
  [ToolCategory.MATH]: MathCategoryIcon,
  [ToolCategory.PRODUCTIVITY]: ProductivityCategoryIcon,
  [ToolCategory.FUN]: FunCategoryIcon,
  [ToolCategory.VIDEO]: VideoCategoryIcon,
  [ToolCategory.MISC]: MiscCategoryIcon,
};

export const CATEGORY_DESCRIPTIONS: Record<ToolCategory, string> = {
  [ToolCategory.TEXT]: "Manipulate text, count words, and more.",
  [ToolCategory.IMAGE]: "Edit, convert, and optimize images.",
  [ToolCategory.CSS]: "Generate CSS code for your projects.",
  [ToolCategory.CODING]: "Format, validate, and convert code.",
  [ToolCategory.COLOR]: "Generate palettes and convert colors.",
  [ToolCategory.MATH]: "Perform calculations and conversions.",
  [ToolCategory.PRODUCTIVITY]: "Boost your efficiency with these tools.",
  [ToolCategory.FUN]: "Have some fun with these generators.",
  [ToolCategory.VIDEO]: "Edit and convert video files.",
  [ToolCategory.MISC]: "Various useful tools.",
};

export const CATEGORY_CONTENT: Record<ToolCategory, { introduction: string }> =
{
  [ToolCategory.TEXT]: {
    introduction: "A collection of tools for text manipulation.",
  },
  [ToolCategory.IMAGE]: { introduction: "Tools for working with images." },
  [ToolCategory.CSS]: { introduction: "Generators for CSS styles." },
  [ToolCategory.CODING]: {
    introduction: "Format, validate, and convert code.",
  },
  [ToolCategory.COLOR]: {
    introduction: "Generate palettes and convert colors.",
  },
  [ToolCategory.MATH]: {
    introduction: "Perform calculations and conversions.",
  },
  [ToolCategory.PRODUCTIVITY]: {
    introduction: "Boost your efficiency with these tools.",
  },
  [ToolCategory.FUN]: {
    introduction: "Have some fun with these generators.",
  },
  [ToolCategory.VIDEO]: { introduction: "Edit and convert video files." },
  [ToolCategory.MISC]: { introduction: "Various useful tools." },
};
