import React from 'react';
import { Tool, ToolCategory } from './types';
import { TOOL_DETAILS } from '@/lib/tool-details';
import {
  AiCategoryIcon,
  AiTokenCounterIcon,
  AiPromptBuilderIcon,
  JsonToPromptIcon,
  CsvToPromptIcon,
  SystemPromptIcon,
  ContextWindowIcon,
  AiModelComparatorIcon,
  PromptLibraryIcon,
  AiTextSummarizerIcon,
  AiOutputFormatterIcon,
  CaseIcon,
  CounterIcon,
  LoremIpsumIcon,
  Base64Icon,
  UrlIcon,
  JsonIcon,
  UuidIcon,
  PasswordIcon,
  ColorIcon,
  ImageIcon,
  TextReverseIcon,
  BoxShadowIcon,
  GradientIcon,
  BorderRadiusIcon,
  TextShadowIcon,
  GlassmorphismIcon,
  HashIcon,
  JwtIcon,
  QrCodeIcon,
  MarkdownIcon,
  DateCalcIcon,
  DiffIcon,
  PomodoroIcon,
  MemeIcon,
  RecipeIcon,
  RegexIcon,
  PaletteIcon,
  UnitConverterIcon,
  BmiIcon,
  TodoIcon,
  CurrencyIcon,
  WorldClockIcon,
  TimersIcon,
  FileConversionIcon,
  TextCategoryIcon,
  ImageCategoryIcon,
  CssCategoryIcon,
  CodeCategoryIcon,
  ColorCategoryIcon,
  MathCategoryIcon,
  ProductivityCategoryIcon,
  FunCategoryIcon,
  MiscCategoryIcon,
  VideoCategoryIcon,
  CharacterCounterIcon,
  KeywordDensityIcon,
  ReadabilityIcon,
  LoanCalculatorIcon,
  TimeZoneConverterIcon,
  VideoCompressorIcon,
  VideoToAudioIcon,
  GifMakerIcon,
  TrimVideoIcon,
  FormatConverterIcon,
  VideoThumbnailIcon,
  VideoMuteIcon,
  WatermarkAdderIcon,
  ImageResizerIcon,
  ImageConverterIcon,
  ImageCompressorIcon,
  CsvToJsonIcon,
  JsonToCsvIcon,
  CsvToXlsxIcon,
  XlsxToCsvIcon,
  WordCounterIcon,
  TerminalIcon,
  CameraToolIcon,
  SqlIcon,
  CronIcon,
  Link2Icon,
  TagIcon,
  ContrastIcon,
  ChmodIcon,
  UtmIcon,
  TriangleIcon,
  XmlIcon,
  MorseIcon,
  BinaryIcon,
  ShieldCheckIcon,
  StringEscaperIcon,
  PercentIcon,
  TableIcon,
  ListIcon,
  EraserIcon,
  AspectRatioIcon,
  FileCodeIcon,
  YoutubeIcon,
  PenIcon,
  TagsIcon,
  FiltersIcon,
  BlobIcon,
  WavesIcon,
  KeyboardIcon,
  ScreenIcon,
  MicIcon,
  RomanIcon,
  BabyIcon,
  DiceIcon,
  DuplicateIcon,
  HtmlEntityIcon,
  CursorIcon,
  DevicesIcon,
  PlaceholderIcon,
  BorderIcon,
  PatternIcon,
  SignatureIcon,
  SeparatorIcon,
  AsciiIcon,
} from '@/components/icons';
import { SeparatorHorizontalIcon } from 'lucide-react';

const PRIVACY_STATEMENT =
  'All calculations and data processing for this tool are performed locally in your browser. We do not send any of your data to our servers, ensuring your information remains private and secure.';

export const TOOLS: Tool[] = [
  // ── AI Tools ──────────────────────────────────────────────────────────────
  {
    id: 'ai-token-counter',
    name: 'AI Token Counter',
    description: 'Count tokens for GPT-4, Claude, Gemini and more. Paste any text or entire documents to see exact token usage before sending to an AI model.',
    seoTitle: 'AI Token Counter — Count Tokens for GPT-4, Claude & Gemini Free',
    seoDescription: 'Free browser-based token counter for every major AI model. Paste unlimited text, see token count, character count, and cost estimate for OpenAI, Anthropic, and Google models — no upload, no API key needed.',
    icon: <AiTokenCounterIcon />,
    category: ToolCategory.AI,
    featured: true,
    keywords: ['token counter', 'ai token counter', 'gpt token counter', 'claude token counter', 'gemini tokens', 'tiktoken online', 'openai tokens', 'llm token count', 'token estimator'],
    tags: ['ai', 'tokens', 'gpt', 'claude', 'gemini', 'llm'],
  },
  {
    id: 'ai-prompt-builder',
    name: 'AI Prompt Builder',
    description: 'Build structured, high-quality prompts for ChatGPT, Claude, and Gemini. Define role, context, task, format, and constraints in a guided form.',
    seoTitle: 'AI Prompt Builder — Build Better Prompts for ChatGPT & Claude',
    seoDescription: 'Free prompt engineering tool. Compose structured prompts with role, context, task, output format, and constraints. Export ready-to-paste prompts for any LLM — no account needed.',
    icon: <AiPromptBuilderIcon />,
    category: ToolCategory.AI,
    featured: true,
    keywords: ['prompt builder', 'ai prompt generator', 'chatgpt prompt', 'prompt engineering', 'claude prompt', 'llm prompt template', 'prompt framework'],
    tags: ['ai', 'prompt', 'chatgpt', 'claude', 'prompt engineering'],
  },
  {
    id: 'json-to-prompt',
    name: 'JSON to AI Prompt',
    description: 'Convert large JSON datasets into clean, token-efficient AI prompts. Perfect for feeding structured data to ChatGPT, Claude, or Gemini without wasting context.',
    seoTitle: 'JSON to AI Prompt Converter — Convert JSON Data for ChatGPT & Claude',
    seoDescription: 'Free tool to convert JSON objects and arrays into natural-language AI prompts. Handles large datasets, lets you choose verbosity level, and produces copy-ready output — runs in your browser.',
    icon: <JsonToPromptIcon />,
    category: ToolCategory.AI,
    featured: false,
    keywords: ['json to prompt', 'json to chatgpt', 'json ai converter', 'convert json to text', 'json to natural language', 'ai data formatter'],
    tags: ['ai', 'json', 'prompt', 'data conversion'],
  },
  {
    id: 'csv-to-prompt',
    name: 'CSV to AI Prompt',
    description: 'Transform CSV files and large tabular datasets into AI-ready prompts. Control which columns to include, row limits, and output format to stay within token budgets.',
    seoTitle: 'CSV to AI Prompt — Convert Spreadsheet Data for ChatGPT & Claude',
    seoDescription: 'Instantly convert CSV or spreadsheet data to a structured AI prompt. Choose columns, set row limits, and get a clean copy-ready prompt for any LLM. Handles files up to 50 MB — fully browser-based.',
    icon: <CsvToPromptIcon />,
    category: ToolCategory.AI,
    featured: false,
    keywords: ['csv to prompt', 'csv to chatgpt', 'csv ai converter', 'spreadsheet to ai', 'tabular data to llm', 'csv to text', 'large dataset ai'],
    tags: ['ai', 'csv', 'prompt', 'data', 'spreadsheet'],
  },
  {
    id: 'ai-system-prompt-generator',
    name: 'System Prompt Generator',
    description: 'Generate professional system prompts for AI assistants, chatbots, and agents. Choose persona, tone, domain, and constraints to produce a production-ready system prompt instantly.',
    seoTitle: 'AI System Prompt Generator — Create System Prompts for ChatGPT & Claude',
    seoDescription: 'Free system prompt generator for AI assistants and chatbots. Select persona, domain, restrictions, and output style to get a ready-to-use system prompt for OpenAI, Anthropic, or any LLM.',
    icon: <SystemPromptIcon />,
    category: ToolCategory.AI,
    featured: false,
    keywords: ['system prompt generator', 'ai system prompt', 'chatbot system prompt', 'openai system prompt', 'claude system prompt', 'ai persona builder', 'custom ai assistant'],
    tags: ['ai', 'system prompt', 'chatbot', 'persona'],
  },
  {
    id: 'context-window-calculator',
    name: 'Context Window Calculator',
    description: 'Calculate whether your text fits within any AI model\'s context window. Compare token usage across GPT-4o, Claude 3.5, Gemini 1.5 Pro, Llama 3, and more.',
    seoTitle: 'Context Window Calculator — Check Token Limits for GPT-4, Claude & Gemini',
    seoDescription: 'Free context window calculator for all major AI models. See how much of your document fits within GPT-4o, Claude 3.5 Sonnet, Gemini 1.5 Pro, and Llama 3 context windows — with visual usage bars.',
    icon: <ContextWindowIcon />,
    category: ToolCategory.AI,
    featured: false,
    keywords: ['context window calculator', 'token limit checker', 'gpt-4 context window', 'claude context window', 'llm context length', 'ai model limits', 'token budget'],
    tags: ['ai', 'context window', 'tokens', 'gpt-4', 'claude'],
  },
  {
    id: 'ai-model-comparator',
    name: 'AI Model Comparator',
    description: 'Compare GPT-4o, Claude 3.5 Sonnet, Gemini 1.5 Pro, Llama 3, Mistral, and more side-by-side. Context window, pricing, strengths, speed, and best use cases.',
    seoTitle: 'AI Model Comparator — Compare GPT-4, Claude, Gemini & Llama Side by Side',
    seoDescription: 'Free AI model comparison tool. Compare context window, token pricing, strengths, and best use cases for GPT-4o, Claude 3.5 Sonnet, Gemini 1.5 Pro, Llama 3, and Mistral — updated 2026.',
    icon: <AiModelComparatorIcon />,
    category: ToolCategory.AI,
    featured: true,
    keywords: ['ai model comparison', 'gpt-4 vs claude', 'claude vs gemini', 'llm comparison', 'best ai model', 'openai vs anthropic', 'ai model pricing', 'chatgpt alternatives'],
    tags: ['ai', 'comparison', 'gpt-4', 'claude', 'gemini', 'llama'],
  },
  {
    id: 'prompt-template-library',
    name: 'Prompt Template Library',
    description: 'Browse 100+ curated, battle-tested AI prompt templates for coding, writing, data analysis, marketing, SEO, and more. Customize and copy in one click.',
    seoTitle: 'AI Prompt Template Library — 100+ Free Prompts for ChatGPT & Claude',
    seoDescription: 'Free library of 100+ prompt templates for ChatGPT, Claude, and Gemini. Covers coding, content writing, data analysis, SEO, emails, debugging, and more. Copy, customize, and paste instantly.',
    icon: <PromptLibraryIcon />,
    category: ToolCategory.AI,
    featured: true,
    keywords: ['prompt templates', 'ai prompts library', 'chatgpt prompts', 'claude prompts', 'prompt examples', 'best ai prompts', 'copy ai prompts', 'productivity prompts'],
    tags: ['ai', 'prompts', 'templates', 'chatgpt', 'productivity'],
  },
  {
    id: 'ai-text-summarizer',
    name: 'AI Text Chunker & Summarizer',
    description: 'Split large documents, PDFs, or articles into AI-ready chunks that fit any model\'s context window. Smart chunking by paragraph, token count, or word limit.',
    seoTitle: 'AI Text Chunker — Split Large Documents for ChatGPT & Claude',
    seoDescription: 'Free browser tool to split large text documents into token-sized chunks for AI models. Upload text up to 10 MB, choose chunk size by tokens or words, and process without any server upload.',
    icon: <AiTextSummarizerIcon />,
    category: ToolCategory.AI,
    featured: false,
    keywords: ['ai text chunker', 'text splitter', 'document chunker', 'split for chatgpt', 'large document ai', 'token chunker', 'context window splitter'],
    tags: ['ai', 'text chunker', 'large documents', 'tokens'],
  },
  {
    id: 'ai-output-formatter',
    name: 'AI Output Formatter',
    description: 'Clean, format, and structure raw AI output. Convert AI-generated JSON, Markdown, or plain text into perfectly formatted, copy-ready content.',
    seoTitle: 'AI Output Formatter — Clean & Format ChatGPT and Claude Responses',
    seoDescription: 'Free tool to format and clean raw AI output. Fix JSON, render Markdown, strip hallucination artifacts, and reformat lists and tables from ChatGPT, Claude, or Gemini responses.',
    icon: <AiOutputFormatterIcon />,
    category: ToolCategory.AI,
    featured: false,
    keywords: ['ai output formatter', 'format chatgpt output', 'ai response formatter', 'clean ai text', 'ai json formatter', 'ai markdown formatter', 'fix ai output'],
    tags: ['ai', 'formatter', 'output', 'json', 'markdown'],
  },
  // ── Original tools follow ───────────────────────────────────────────────
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    description: 'Instantly generate TypeScript interfaces from JSON objects.',
    seoTitle: 'JSON to TypeScript Converter 📜 | Generate Interfaces Instantly',
    seoDescription:
      'Convert JSON objects into TypeScript interfaces instantly. Our free online tool handles nested objects and arrays, saving you time. 100% private and secure.',
    icon: <JsonIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'json to typescript',
      'json to ts',
      'typescript interface generator',
      'json to types',
      'convert json to typescript',
      'json to interface',
    ],
  },
  {
    id: 'code-to-image',
    name: 'Code to Image',
    description: 'Create beautiful images of your code snippets for sharing.',
    seoTitle: 'Code to Image Converter 📸 | Create Beautiful Code Snippets',
    seoDescription:
      'Turn your code into beautiful, shareable images. Customize themes, fonts, and backgrounds with our free online Code to Image tool. Perfect for social media.',
    icon: <CameraToolIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'code to image',
      'code snippet image',
      'source code to image',
      'carbon alternative',
      'code screenshot generator',
      'syntax highlighting image',
    ],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify your SQL queries.',
    seoTitle: 'Online SQL Formatter 💾 | Beatify & Format SQL Queries',
    seoDescription:
      'Format and beautify your SQL queries instantly online. Support for MySQL, PostgreSQL, SQL Server, and more. Clean up messy code with our free SQL Formatter.',
    icon: <SqlIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'sql formatter',
      'sql beautifier',
      'format sql online',
      'prettify sql',
      'sql syntax highlighter',
      'sql query formatter',
    ],
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    description: 'Visually build and explain cron job schedules.',
    seoTitle: 'Cron Expression Generator ⏳ | Visual Cron Job Editor',
    seoDescription:
      'Create and learn cron expressions with our easy-to-use visual generator. Schedule jobs for Linux/Unix systems without syntax errors. Free and instant.',
    icon: <CronIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'cron generator',
      'cron expression editor',
      'crontab generator',
      'schedule cron job',
      'cron syntax helper',
      'linux cron scheduler',
    ],
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Convert text into SEO-friendly URL slugs.',
    seoTitle: 'URL Slug Generator 🐌 | SEO Friendly URL Converter',
    seoDescription:
      'Instantly create clean, SEO-friendly URL slugs from any text. Remove special characters and optimize your links for better search ranking. Free and private.',
    icon: <Link2Icon />,
    category: ToolCategory.TEXT,
    keywords: [
      'slug generator',
      'url slug creator',
      'seo url builder',
      'text to slug',
      'create clean url',
      'hyphenate text',
    ],
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags for your website.',
    seoTitle: 'Meta Tag Generator 🏷️ | Free SEO Meta Tags Builder',
    seoDescription:
      'Generate perfect SEO meta tags for your website in seconds. Create title, description, keywords, and Open Graph tags to boost your search rankings.',
    icon: <TagIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'meta tag generator',
      'seo meta tags',
      'open graph generator',
      'meta description builder',
      'social media meta tags',
      'html meta tag builder',
    ],
  },
  {
    id: 'contrast-checker',
    name: 'Contrast Checker',
    description: 'Check color contrast accessibility (WCAG).',
    seoTitle: 'Center Color Contrast Checker 🌗 | WCAG Accessibility Tester',
    seoDescription:
      'Check the contrast ratio between text and background colors. Ensure your design meets WCAG accessibility standards with our free online Contrast Checker.',
    icon: <ContrastIcon />,
    category: ToolCategory.COLOR,
    keywords: ['contrast checker', 'wcag', 'accessibility', 'color contrast', 'a11y'],
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Visual calculator for Unix file permissions.',
    seoTitle: 'Chmod Calculator 🔐 | Unix File Permissions generator',
    seoDescription:
      'Calculate numeric (octal) and symbolic (rwx) file permissions for Unix/Linux systems. Visual Chmod Calculator makes setting permissions safe and easy.',
    icon: <ChmodIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'chmod calculator',
      'linux permissions calculator',
      'chmod generator',
      'unix file permissions',
      'octal permissions tool',
      'chmod 777 explanation',
    ],
  },
  {
    id: 'utm-builder',
    name: 'UTM Builder',
    description: 'Build tracking URLs for marketing campaigns.',
    seoTitle: 'Free UTM Builder 🔗 | Campaign URL Generator for GA4 & Google Analytics',
    seoDescription:
      'Build trackable campaign URLs in seconds. Add utm_source, medium & campaign tags, force lowercase for clean GA4 data, and copy with one click. Free, private, and no sign-up — with ready-made presets for Google Ads, Facebook, and email.',
    icon: <UtmIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      'utm builder',
      'utm link builder',
      'campaign url builder',
      'utm parameter generator',
      'google analytics url builder',
      'ga4 campaign tracking',
      'utm code generator',
      'utm tag builder',
      'marketing campaign tracking',
    ],
  },
  {
    id: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate dimensions and aspect ratios for images and video.',
    seoTitle: 'Aspect Ratio Calculator 📐 | Resize Images & Video',
    seoDescription:
      'Calculate aspect ratios and dimensions for images and videos instantly. Essential tool for designers and video editors to find precise width and height.',
    icon: <AspectRatioIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'aspect ratio calculator',
      'image dimension calculator',
      '16:9 calculator',
      'resize calculator',
      'video aspect ratio tool',
      'calculate height from width',
    ],
  },
  {
    id: 'css-triangle-generator',
    name: 'CSS Triangle Generator',
    description: 'Generate CSS code for geometric triangles.',
    seoTitle: 'CSS Triangle Generator 🔺 | Create Pure CSS Triangles',
    seoDescription:
      'Generate pure CSS triangles in any direction and color. Adjust size and copy the code instantly. No images required.',
    icon: <TriangleIcon />,
    category: ToolCategory.CSS,
    keywords: ['css triangle', 'triangle generator', 'css shapes', 'border triangle'],
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Beautify and format XML strings.',
    seoTitle: 'XML Formatter Online 📄 | Free XML Beautifier, Validator & Minifier',
    seoDescription:
      'Paste XML and instantly beautify, validate, or minify it. Choose 2/4-space or tab indentation, catch syntax errors with line-level messages, upload files, and download the result. 100% browser-based — your data never leaves your machine.',
    icon: <XmlIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'xml formatter',
      'xml beautifier',
      'format xml online',
      'xml prettifier',
      'xml validator',
      'xml minifier',
      'pretty print xml',
      'xml syntax highlight',
      'online xml editor',
    ],
  },
  {
    id: 'morse-converter',
    name: 'Morse Code Converter',
    description: 'Translate text to Morse code and vice versa.',
    seoTitle: 'Morse Code Converter 📡 | Text to Morse & Morse to Text',
    seoDescription:
      'Convert text to Morse code and decode Morse code back to text. Listen to the audio and learn the alphabet. Free online tool.',
    icon: <MorseIcon />,
    category: ToolCategory.FUN,
    keywords: ['morse code', 'morse converter', 'text to morse', 'morse translator'],
  },
  {
    id: 'binary-converter',
    name: 'Binary Converter',
    description: 'Translate text to binary code and back.',
    seoTitle: 'Binary Converter 0️⃣1️⃣ | Text to Binary & Binary to Text',
    seoDescription:
      'Convert text to binary code (0s and 1s) and decode binary back to text. Understand computer data representation with this free tool.',
    icon: <BinaryIcon />,
    category: ToolCategory.CODING,
    keywords: ['binary converter', 'text to binary', 'binary to text', 'binary code'],
  },
  {
    id: 'password-strength',
    name: 'Password Strength Checker',
    description: 'Test the strength of your passwords.',
    seoTitle: 'Password Strength Checker 💪 | Test Password Security',
    seoDescription:
      'Check how strong your password is against cracking attacks. Get instant feedback and tips to improve security. 100% processing in browser.',
    icon: <ShieldCheckIcon />,
    category: ToolCategory.MISC,
    keywords: ['password strength', 'password checker', 'password security', 'strong password'],
  },
  {
    id: 'string-escaper',
    name: 'String Escaper',
    description: 'Escape strings for JSON, HTML, URL, and Java.',
    seoTitle: 'String Escaper 📝 | Escape JSON, HTML, and URL Strings',
    seoDescription:
      'Quickly escape special characters for JSON, HTML, URLs, Java, and JavaScript. Prevent syntax errors and security issues with our free String Escaper.',
    icon: <StringEscaperIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'string escaper',
      'json escape tool',
      'html escape string',
      'url escape characters',
      'java string escaper',
      'escape special characters',
    ],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Quickly calculate percentages for common math problems.',
    seoTitle: 'Percentage Calculator % | Online Percent Change & Amount',
    seoDescription:
      'Calculate percentages, percent change, and fractions of numbers instantly. Simple, free online percentage calculator for daily math.',
    icon: <PercentIcon />,
    category: ToolCategory.MATH,
    keywords: ['percentage calculator', 'percent calculator', 'calculate percentage', 'percent change'],
  },
  {
    id: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    description: 'Create Markdown tables easily with a visual editor.',
    seoTitle: 'Markdown Table Generator ▦ | Visual Markdown Table Editor',
    seoDescription:
      'Easily create and format Markdown tables with our free visual editor. Convert CSV or Excel data to Markdown instantly. Perfect for READMEs and documentation.',
    icon: <TableIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      'markdown table generator',
      'convert csv to markdown',
      'excel to markdown table',
      'visual markdown editor',
      'table to markdown',
      'generate md table',
    ],
  },
  {
    id: 'list-randomizer',
    name: 'List Randomizer',
    description: 'Shuffle and randomize a list of items.',
    seoTitle: 'List Randomizer 🎲 | Shuffle Lists & Pick Winners',
    seoDescription:
      'Randomize and shuffle any list of items instantly. Perfect for raffles, lottery picks, or mixing content. Fair and unbiased shuffling.',
    icon: <ListIcon />,
    category: ToolCategory.FUN,
    keywords: ['list randomizer', 'shuffle list', 'random picker', 'raffle tool'],
  },
  {
    id: 'text-cleaner',
    name: 'Text Cleaner',
    description: 'Remove extra spaces, line breaks, and format text.',
    seoTitle: 'Text Cleaner Tool 🧹 | Remove Spaces, Breaks & Formatting',
    seoDescription:
      'Clean and format your text instantly. Remove extra spaces, line breaks, HTML tags, and more with our free online Text Cleaner. Perfect for writers and developers.',
    icon: <EraserIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      'text cleaner online',
      'remove line breaks',
      'remove extra spaces',
      'clean text formatting',
      'strip html tags',
      'normalize text',
    ],
  },

  {
    id: 'svg-to-data-uri',
    name: 'SVG to Data URI',
    description: 'Convert SVG code into a Data URI for use in CSS backgrounds and HTML.',
    seoTitle: 'SVG to Data URI Converter 🖼️ | Encode SVG for CSS Instantly',
    seoDescription:
      'Free SVG to Data URI converter. Transform SVG code into base64 Data URIs instantly for embedding in CSS or HTML. Optimize web performance with inline SVGs.',
    icon: <ImageIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'svg to data uri',
      'svg to data url',
      'svg encoder',
      'svg to base64',
      'embed svg in css',
      'svg data url generator',
      'optimize svg for web',
      'inline svg converter',
    ],
  },
  {
    id: 'json-yaml-converter',
    name: 'JSON <> YAML Converter',
    description: 'Convert between JSON and YAML.',
    seoTitle: 'JSON <> YAML Converter 🔄 | Bidirectional Conversion',
    seoDescription:
      'Convert JSON to YAML and YAML to JSON instantly. Our free online tool ensures accurate conversion for configuration files and data structures.',
    icon: <FileCodeIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'json to yaml',
      'yaml to json',
      'convert json to yaml',
      'convert yaml to json',
      'yaml converter',
      'json converter',
    ],
  },
  // Batch 3
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail Downloader',
    description: 'Download thumbnails from any YouTube video in max resolution.',
    seoTitle: 'YouTube Thumbnail Downloader 🖼️ | Save HD Thumbnails',
    seoDescription:
      'Download high-quality thumbnails from any YouTube video. Get Max Res, HD, SD, and default sizes instantly. fast, free, and easy to use.',
    icon: <YoutubeIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'youtube thumbnail downloader',
      'save youtube thumbnail',
      'download video cover',
      'get youtube thumbnail image',
      'hd thumbnail grabber',
      'youtube image extractor',
    ],
  },
  {
    id: 'fancy-font-generator',
    name: 'Fancy Font Generator',
    description: 'Generate stylish text for social media bios.',
    seoTitle: 'Fancy Font Generator ✒️ | Stylish Text for Instagram & Bio',
    seoDescription:
      'Generate cool, fancy text styles for your Instagram bio, Twitter, and other social media. Copy and paste stylish fonts with our free online generator.',
    icon: <PenIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      'fancy font generator',
      'instagram font generator',
      'cool text generator',
      'stylish text maker',
      'aesthetic font copy paste',
      'bio font changer',
    ],
  },
  {
    id: 'hashtag-extractor',
    name: 'Hashtag Extractor',
    description: 'Extract hashtags from a block of text.',
    seoTitle: 'Hashtag Extractor #️⃣ | Find Hashtags in Text Instantly',
    seoDescription:
      'Instantly extract all hashtags from any text block. Perfect for social media managers and marketers to analyze and collect tags from posts.',
    icon: <TagsIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      'hashtag extractor',
      'find hashtags in text',
      'extract tags from instagram',
      'hashtag finder tool',
      'social media tag extractor',
      'grab hashtags',
    ],
  },
  {
    id: 'image-filters',
    name: 'Instagram Photo Filters',
    description: 'Apply CSS filters like grayscale, sepia, and blur to images.',
    seoTitle: 'Online Image Filters 🎨 | Apply Instagram-like Effects',
    seoDescription:
      'Enhance your photos with free online filters. Apply Grayscale, Sepia, Blur, Brightness, and more instantly directly in your browser.',
    icon: <FiltersIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'online photo filters',
      'css image filters',
      'instagram filters online',
      'image effects tool',
      'grayscale converter',
      'photo editor online',
    ],
  },
  {
    id: 'svg-blob-generator',
    name: 'SVG Blob Generator',
    description: 'Create organic blob shapes for backgrounds.',
    seoTitle: 'SVG Blob Generator 💧 | Create Organic Shapes',
    seoDescription:
      'Generate unique, organic SVG blobs for your web design backgrounds. Customize complexity and contrast to create the perfect shape. Free and open-source.',
    icon: <BlobIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'svg blob generator',
      'organic shape generator',
      'blob maker',
      'svg background shapes',
      'web design blobs',
      'random blob creator',
    ],
  },
  {
    id: 'svg-wave-generator',
    name: 'SVG Wave Generator',
    description: 'Generate smooth wave dividers for your website.',
    seoTitle: 'SVG Wave Generator 🌊 | Create Website Section Dividers',
    seoDescription:
      'Create beautiful SVG waves for your website headers and footers. Customize layers, height, and color to generate the perfect wave divider.',
    icon: <WavesIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'svg wave generator',
      'website divider generator',
      'css wave shape',
      'svg path generator',
      'wave background maker',
      'section separator',
    ],
  },
  {
    id: 'keycode-info',
    name: 'Keycode Event Info',
    description: 'Get JavaScript event codes for any key press.',
    seoTitle: 'Keycode Info ⌨️ | JavaScript Key Events & Codes',
    seoDescription:
      'Press any key to get its JavaScript KeyCode, code, key, and other event properties. Essential tool for web developers handling keyboard events.',
    icon: <KeyboardIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'javascript keycode',
      'keyboard event viewer',
      'key code checker',
      'js keyboard events',
      'find key code',
      'keyboard test',
    ],
  },
  {
    id: 'screen-info',
    name: 'Screen Resolution Info',
    description: 'View your current screen and viewport dimensions.',
    seoTitle: 'Screen Resolution Info 🖥️ | My Screen & Viewport Size',
    seoDescription:
      'Instantly detect your screen resolution, browser viewport size, device pixel ratio, color depth, and orientation. Free "what is my screen resolution" checker — copy all values as JSON.',
    icon: <ScreenIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      'what is my screen resolution',
      'screen resolution checker',
      'viewport size',
      'device pixel ratio',
      'browser window size',
      'display info',
    ],
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to spoken audio in your browser using local AI.',
    seoTitle: 'Free Text to Speech Converter 🗣️ | AI Voice Generator Online',
    seoDescription:
      'Convert text to lifelike speech instantly. Free, browser-based AI TTS with batch processing and Kokoro, Piper, and Sherpa ONNX engines. No signup.',
    icon: <MicIcon />,
    category: ToolCategory.FUN,
    keywords: [
      'text to speech online',
      'free tts tool',
      'ai voice generator',
      'convert text to audio',
      'read text aloud',
      'browser tts',
      'speech synthesis',
      'batch tts generator',
      'kokoro tts online',
      'piper tts',
      'sherpa onnx tts',
      'local ai voice',
      'text to mp3',
      'natural sounding voice',
    ],
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert numbers to Roman numerals and back.',
    seoTitle: 'Roman Numeral Converter 🏛️ | Numbers to Roman Numerals',
    seoDescription:
      'Convert standard numbers to Roman numerals (I, V, X, L, C, D, M) and vice versa. Learn the rules and convert dates instantly.',
    icon: <RomanIcon />,
    category: ToolCategory.MATH,
    keywords: ['roman numerals', 'roman converter', 'numbers to roman', 'roman to numbers'],
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, and days.',
    seoTitle: 'Age Calculator 🎂 | Calculate Exact Age from Date of Birth',
    seoDescription:
      'Find out exactly how old you are in years, months, days, hours, and minutes. Calculate the time until your next birthday.',
    icon: <BabyIcon />,
    category: ToolCategory.MATH,
    keywords: ['age calculator', 'calculate age', 'date of birth', 'age from dob'],
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers within a specific range.',
    seoTitle: 'Random Number Generator 🎲 | RNG Online',
    seoDescription:
      'Generate true random numbers within a custom range. Set minimum and maximum values and generate multiple numbers instantly.',
    icon: <DiceIcon />,
    category: ToolCategory.MATH,
    keywords: ['random number generator', 'rng', 'random numbers', 'number generator'],
  },
  {
    id: 'duplicate-remover',
    name: 'Duplicate Line Remover',
    description: 'Remove duplicate entries from a list of text.',
    seoTitle: 'Duplicate Line Remover ✂️ | Remove Duplicate Lines Online',
    seoDescription:
      'Instantly remove duplicate lines from your text list. Clean up data, emails, or inventory lists with our free, secure duplicate remover tool.',
    icon: <DuplicateIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      'duplicate remover',
      'remove duplicate lines',
      'deduplicate text',
      'list cleaner',
      'delete duplicates online',
      'unique line filter',
    ],
  },
  {
    id: 'html-entity',
    name: 'HTML Entity Encoder',
    description: 'Encode/Decode text to HTML entities.',
    seoTitle: 'HTML Entity Encoder/Decoder 🔡 | Escape HTML Characters',
    seoDescription:
      'Convert text to HTML entities and back. Safely escape special characters like <, >, and & for use in web pages. Free, fast, and secure.',
    icon: <HtmlEntityIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'html entity encoder',
      'html decode',
      'escape html characters',
      'html special characters',
      'convert to html entities',
      'xml entity encoder',
    ],
  },
  {
    id: 'css-cursors',
    name: 'CSS Cursor Viewer',
    description: 'Visual reference for all CSS cursor types.',
    seoTitle: 'CSS Cursor Viewer 🖱️ | Visual Guide to CSS Cursors',
    seoDescription:
      'Interactive guide to all CSS cursor properties. Hover over items to see pointer, help, wait, grab, and other cursor styles in action.',
    icon: <CursorIcon />,
    category: ToolCategory.CSS,
    keywords: ['css cursor', 'cursor styles', 'mouse pointer', 'cursor property'],
  },
  {
    id: 'device-resolutions',
    name: 'Device Resolution List',
    description: 'Reference guide for common device screen sizes.',
    seoTitle: 'Device Screen Resolutions 📱 | Viewport Size Reference',
    seoDescription:
      'List of common screen resolutions and viewport sizes for mobile, tablet, and desktop devices. Essential reference for responsive web design.',
    icon: <DevicesIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: ['device resolutions', 'screen sizes', 'viewport sizes', 'responsive design'],
  },
  {
    id: 'lorem-image-generator',
    name: 'Lorem Picsum Generator',
    description: 'Generate placeholder image URLs.',
    seoTitle: 'Lorem Picsum Generator 🏞️ | Random Placeholder Images',
    seoDescription:
      'Generate random, high-quality placeholder images for your web designs. Get customizable URLs for specific sizes and effects (grayscale, blur).',
    icon: <PlaceholderIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'placeholder image generator',
      'lorem picsum tool',
      'random image url',
      'dummy image generator',
      'web design placeholders',
      'mockup images',
    ],
  },
  {
    id: 'css-borders',
    name: 'CSS Border Preview',
    description: 'Visualizer for all CSS border styles.',
    seoTitle: 'CSS Border Preview 🖼️ | Visual Border Style Generator',
    seoDescription:
      'Visualize and generate all CSS border styles. Test solid, dashed, dotted, double, groove, ridge, inset, and outset borders instantly.',
    icon: <BorderIcon />,
    category: ToolCategory.CSS,
    keywords: ['css borders', 'border styles', 'border generator', 'css border preview'],
  },
  {
    id: 'css-patterns',
    name: 'CSS Background Patterns',
    description: 'Generate pure CSS background patterns.',
    seoTitle: 'CSS Pattern Generator 🏁 | Pure CSS Backgrounds',
    seoDescription:
      'Create lightweight, scalable background patterns with pure CSS. No images required. Copy the code for stripes, checks, dots, and more.',
    icon: <PatternIcon />,
    category: ToolCategory.CSS,
    keywords: ['css patterns', 'background patterns', 'css backgrounds', 'pattern generator'],
  },
  {
    id: 'signature-pad',
    name: 'Signature Pad',
    description: 'Draw and save digital signatures.',
    seoTitle: 'Online Signature Pad ✍️ | Draw & Download Signatures',
    seoDescription:
      'Draw your signature online and download it as a transparent PNG. Perfect for signing documents digitally. Works on mobile and desktop.',
    icon: <SignatureIcon />,
    category: ToolCategory.MISC,
    keywords: ['signature pad', 'digital signature', 'sign online', 'signature generator'],
  },
  // ... rest of the existing tools (ensure Readability Score, Loan Calculator, etc. are preserved)
  {
    id: 'readability-score-calculator',
    name: 'Flesch-Kincaid /Readability Score Calculator',
    description:
      'Analyze text complexity and calculate Flesch-Kincaid and other readability scores to improve content clarity and accessibility.',
    seoTitle: 'Flesch-Kincaid Grade Level Readability Calculator',
    seoDescription:
      'Check your text readability instantly using Flesch Reading Ease and Flesch-Kincaid Grade Level. Free online readability score calculator. No signup required.',
    icon: <ReadabilityIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      'readability score calculator',
      'flesch kincaid readability',
      'readability checker online',
      'text grade level checker',
      'content readability tool',
      'reading ease score',
      'writing clarity analyzer',
      'text complexity checker',
      'writing score',
      'content accessibility',
    ],
  },
  {
    id: 'loan-calculator',
    name: 'Loan Calculator',
    description:
      'Calculate accurate monthly payments, interest costs, and a complete amortization schedule for any type of loan.',
    seoTitle: 'Free Loan Calculator — Monthly Payments & Amortization',
    seoDescription:
      'Estimate monthly payments, total interest, and a full amortization schedule for mortgages, car loans, and more. Fast, accurate, and 100% private.',

    icon: <LoanCalculatorIcon />,
    category: ToolCategory.MATH,

    keywords: [
      'loan calculator',
      'monthly payment calculator',
      'loan amortization calculator',
      'mortgage payment calculator',
      'car loan calculator',
      'interest rate calculator',
      'principal and interest calculator',
      'loan repayment schedule',
      'financial planning tool',
    ],
  },
  {
    id: 'timezone-converter',
    name: 'Time Zone Converter',
    description:
      'Instantly convert any date and time between global time zones with precise, real-time accuracy.',
    seoTitle: 'Time Zone Converter — Convert Time Between Cities',
    seoDescription:
      'Convert time between any cities in the world. Perfect for scheduling meetings, planning travel, and staying in sync with global teams.',
    icon: <TimeZoneConverterIcon />,
    category: ToolCategory.PRODUCTIVITY,

    keywords: [
      'time zone converter',
      'timezone calculator',
      'world time converter',
      'time difference calculator',
      'international meeting scheduler',
      'gmt to ist converter',
      'pst to est converter',
      'utc time converter',
      'global clock',
      'remove duplicates',
      'text cleaner',
    ],
  },
  {
    id: 'comma-separator',
    name: 'Comma Separator',
    description: 'Convert lists to comma-separated text with advanced formatting.',
    seoTitle: 'Comma Separator 📝 | Convert Column to Comma Separated List',
    seoDescription:
      'Free online tool to convert lists to comma-separated values (CSV) and vice versa. Support for custom delimiters, wrapping, sorting, and duplicate removal.',
    icon: <SeparatorHorizontalIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      'comma separator',
      'column to comma',
      'list to csv',
      'delimiter converter',
      'text joiner',
      'split text',
      'delim.co alternative',
    ],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between uppercase, lowercase, title case, and more formats.',
    seoTitle: 'Online Case Converter 🔠 | Instantly Change Text Case',
    seoDescription:
      'Quickly convert text to UPPERCASE, lowercase, Title Case, Sentence case, and more with our free online tool. Perfect for headlines, essays, and code. 100% private and easy to use.',
    icon: <CaseIcon />,
    category: ToolCategory.TEXT,
    featured: true,
    keywords: [
      'text case converter',
      'change case online',
      'uppercase to lowercase',
      'title case generator',
      'sentence case tool',
      'text formatting',
    ],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description:
      'Instantly count words, characters, sentences, and paragraphs with our advanced, real-time Word Counter tool.',
    seoTitle: 'Free Online Word Counter 🔢 | Real-Time Word & Character Count',
    seoDescription:
      'Instant, accurate counts for words, characters, sentences, and paragraphs, plus estimated reading time. For writers, students, and SEOs.',
    icon: <WordCounterIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      'word counter',
      'word count tool',
      'character counter',
      'letter count tool',
      'online word counter',
      'sentence counter',
      'paragraph counter',
      'text analysis tool',
      'reading time calculator',
      'speaking time calculator',
      'SMS character counter',
      'Twitter character counter',
      'meta description length checker',
      'title tag length checker',
      'byte size calculator',
      'content writing tool',
    ],
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description:
      'Generate customizable placeholder text for web design, UI/UX prototypes, print layouts, and content mockups.',
    seoTitle: 'Lorem Ipsum Generator 📄 | Create Custom Placeholder Text',
    seoDescription:
      'Need placeholder text? Our free Lorem Ipsum Generator creates custom dummy text for your designs. Generate paragraphs, sentences, or words to perfect your layouts. Fast, easy, and professional.',
    icon: <LoremIpsumIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      'lorem ipsum generator',
      'placeholder text generator',
      'dummy text creator',
      'mockup text tool',
      'filler text generator',
      'UI/UX placeholder text',
      'web design dummy text',
      'design content filler',
    ],
  },
  {
    id: 'text-reverser',
    name: 'Text Reverser',
    description:
      'Instantly reverse any string of text, words, letters, or symbols for fun, puzzles, or programming tasks.',
    seoTitle: 'Online Text Reverser 🔄 | Reverse Words, Letters & Strings',
    seoDescription:
      'Flip your text backwards with our free Text Reverser. Instantly reverse words, letters, and even emojis. Perfect for fun social media posts, puzzles, or coding challenges.',
    icon: <TextReverseIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      'text reverser online',
      'reverse words tool',
      'string reverser',
      'backwards text generator',
      'mirror text creator',
      'flip letters online',
      'reverse string tool',
      'unicode text reverser',
    ],
  },
  {
    id: 'markdown-previewer',
    name: 'Markdown Previewer',
    description:
      'Write Markdown and instantly see the rendered HTML in a live, real-time preview for documentation, blogs, and READMEs.',
    seoTitle: 'Live Markdown Editor 📝 | Real-Time Markdown Previewer',
    seoDescription:
      'Write and preview Markdown side-by-side with our free live editor. Instantly see how your text will look as HTML. Perfect for READMEs, blogs, and documentation. Fast, secure, and easy to use.',
    icon: <MarkdownIcon />,
    category: ToolCategory.TEXT,

    keywords: [
      'markdown editor online',
      'live markdown preview',
      'markdown to html converter',
      'readme editor',
      'md file viewer',
      'markdown live editor',
      'markdown documentation tool',
      'markdown blog preview',
    ],
  },
  // Coding Tools
  {
    id: 'base64-converter',
    name: 'Base64 Converter',
    description: 'Instantly encode and decode text, images, and files to/from Base64 online.',
    seoTitle: 'Online Base64 Converter 📦 | Encode & Decode Text, Files & Images',
    seoDescription:
      'A free, powerful tool to encode and decode Base64. Easily convert text, images, or any file into a Base64 string and back again. Secure, fast, and all in your browser.',
    icon: <Base64Icon />,
    category: ToolCategory.CODING,
    keywords: [
      'base64 converter online',
      'encode text to base64',
      'decode base64 string',
      'file to base64 converter',
      'data uri generator online',
      'base64 image',
    ],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode strings for safe URL transmission online.',
    seoTitle: 'Online URL Encoder & Decoder 🔗 | Percent-Encoding Tool',
    seoDescription:
      'Quickly and safely encode or decode strings for use in URLs. Our free tool handles special characters and spaces, preventing broken links. Perfect for developers and marketers.',
    icon: <UrlIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'url encoder decoder online',
      'percent encoding tool',
      'url safe encoding',
      'encodeURIComponent online',
      'query string encoder',
      'url escape tool',
    ],
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Validate, format, and pretty-print your JSON data instantly online.',
    seoTitle: 'Online JSON Formatter 📋 | Validate & Beautify JSON',
    seoDescription:
      'Clean up your messy JSON with our free online formatter. Instantly validate, format, and beautify your JSON data to make it readable. Perfect for developers debugging APIs.',
    icon: <JsonIcon />,
    category: ToolCategory.CODING,
    featured: true,
    keywords: [
      'json formatter online',
      'json validator',
      'pretty print json online',
      'json beautifier tool',
      'json viewer online',
      'json lint',
    ],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions against strings online.',
    seoTitle: 'Online Regex Tester 🔍 | Test & Debug Regular Expressions',
    seoDescription:
      'Test your regular expressions in real-time with our free online Regex Tester. Instantly see matches and capture groups highlighted. Perfect for developers and data analysts. 100% private.',
    icon: <RegexIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'regex tester online',
      'regular expression tester',
      'javascript regex checker',
      'validate regex pattern',
      'regex debugger online',
      'regex live test',
    ],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate secure, random UUIDs (v4) online instantly.',
    seoTitle: 'Online UUID Generator 🆔 | Instantly Create Random UUIDs (v4)',
    seoDescription:
      'Need a unique ID? Our free UUID Generator creates random, secure Version 4 UUIDs in a single click. Perfect for databases, session IDs, and any application needing a unique identifier.',
    icon: <UuidIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'uuid generator online',
      'generate uuid v4',
      'random uuid online',
      'guid generator',
      'unique identifier generator',
      'crypto.randomuuid',
    ],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Create SHA-1, SHA-256, or SHA-512 hashes online from any text.',
    seoTitle: 'Online Hash Generator 🗝️ | Generate SHA-1, SHA-256 & SHA-512 Hashes',
    seoDescription:
      'Instantly generate secure SHA-1, SHA-256, and SHA-512 hashes from any text with our free online tool. Powered by the Web Crypto API for maximum security. 100% private.',
    icon: <HashIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'sha256 generator online',
      'sha512 hash calculator',
      'sha1 generator online',
      'string to hash',
      'web crypto hash tool',
      'text to sha256',
    ],
  },
  {
    id: 'jwt-debugger',
    name: 'JWT Decoder',
    description: 'Decode JSON Web Tokens to view header and payload online.',
    seoTitle: 'Online JWT Decoder 🔐 | Decode & Inspect JSON Web Tokens',
    seoDescription:
      'Instantly decode and inspect JSON Web Tokens (JWTs) with our free online tool. View the header and payload in a readable format. Perfect for debugging authentication tokens. 100% private.',
    icon: <JwtIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'jwt decoder online',
      'json web token decoder',
      'inspect jwt payload',
      'decode jwt online',
      'auth token debugger',
      'jwt.io alternative',
    ],
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Instantly compare text or code and highlight every difference in seconds.',
    seoTitle: 'Diff Checker Online ⚖️ | Compare Text & Code Side-by-Side',
    seoDescription:
      'Free online diff checker to compare two blocks of text or code. Instantly highlight differences, track changes, and find edits. Secure, fast, and 100% private.',
    icon: <DiffIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'diff checker',
      'diff_checker',
      'dff checker',
      'diff tool online',
      'compare text',
      'compare code',
      'track changes',
      'highlight differences',
      'text comparison tool',
      'code diff online',
    ],
  },
  {
    id: 'json-csv-converter',
    name: 'JSON <> CSV Converter',
    description: 'Convert between JSON and CSV formats instantly.',
    seoTitle: 'Online JSON <> CSV Converter 📊 | Free & Instant',
    seoDescription:
      'Effortlessly convert between JSON and CSV formats with our free online tool. Perfect for developers and data analysts. Fast, secure, and browser-based.',
    icon: <CsvToJsonIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'csv to json online',
      'json to csv online',
      'convert csv to json',
      'convert json to csv',
      'csv parser',
      'data transformation tool',
    ],
  },
  {
    id: 'csv-xlsx-converter',
    name: 'Data Converter',
    description:
      'The ultimate data conversion tool. Convert CSV or XLSX files to JSON, SQL, HTML, and more, instantly in your browser.',
    seoTitle: 'Convert CSV, XLSX, JSON, SQL, and more 🔁 | Universal Data Converter',
    seoDescription:
      'Our free online Data Converter instantly transforms your files. Convert CSV or Excel (XLSX) to JSON, SQL, HTML, Markdown, and more. Secure, browser-based, and incredibly fast.',
    icon: <FileConversionIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'data converter',
      'file converter',
      'csv to json',
      'xlsx to csv',
      'csv to sql',
      'excel to json',
      'json to csv',
      'data transformation',
      'file format converter',
      'browser-based tools',
    ],
  },
  // Image Tools
  {
    id: 'image-to-base64',
    name: 'Image ⇄ Base64 Converter',
    description: 'Encode an image to a Base64 data URL, or decode Base64 back into a viewable image.',
    seoTitle: 'Image to Base64 Converter 🖼️ | Encode & Decode Base64 Images Online',
    seoDescription:
      'Convert any image (PNG, JPG, SVG, GIF, WebP) to a Base64 data URL, or decode Base64 back into a viewable, downloadable image. Switch direction with one click — perfect for embedding images in HTML/CSS. 100% private, no upload.',
    icon: <ImageIcon />,
    category: ToolCategory.IMAGE,
    featured: true,
    keywords: [
      'image to base64 converter',
      'base64 to image converter',
      'data uri generator',
      'decode base64 to image',
      'embed image in html',
      'css background image base64',
      'png to base64',
      'jpg to base64',
      'view base64 image',
    ],
  },
  // CSS Tools
  {
    id: 'box-shadow-generator',
    name: 'Box Shadow Generator',
    description: 'Create and customize CSS box-shadow effects with a visual editor.',
    seoTitle: 'CSS Box Shadow Generator 🌑 | Online Preview & Code',
    seoDescription:
      'Design perfect CSS box-shadows with our free visual generator. Visual editor for offsets, blur, spread, and color. Copy paste beautiful shadow code instantly.',
    icon: <BoxShadowIcon />,
    category: ToolCategory.CSS,
    keywords: [
      'css box shadow generator',
      'box shadow preview',
      'css shadow creator',
      'box-shadow generator online',
      'copy paste box shadow',
      'beautiful css shadows',
      'inset shadow generator',
      'css ui generator',
    ],
  },
  {
    id: 'css-gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Create beautiful CSS gradients with color pickers and angle controls.',
    seoTitle: 'CSS Gradient Generator 🌈 | Create Beautiful Gradients Online',
    seoDescription:
      'Design stunning linear and radial CSS gradients with our free visual editor. Add multiple colors, control angles, and get production-ready code instantly. Perfect for modern web design.',
    icon: <GradientIcon />,
    category: ToolCategory.CSS,
    keywords: [
      'css gradient generator',
      'gradient generator online',
      'css gradient background generator',
      'linear gradient css generator',
      'radial gradient css generator',
      'conic gradient generator',
      'css gradient code generator',
      'gradient background maker for website',
      'css gradient editor live preview',
      'animated css gradient generator',
      'gradient button generator css',
      'css gradient tutorial for beginners',
      'generate css gradient code free',
      'multi color css gradient generator',
      'best css gradient generator 2025',
      'how to make css gradient background',
      'css gradient maker with angle control',
      'css gradient presets for UI design',
      'copy css gradient code',
      'css gradient generator for tailwind',
    ],
  },
  {
    id: 'border-radius-generator',
    name: 'Border Radius Generator',
    description: 'Create custom border radius values with individual corner controls.',
    seoTitle: 'CSS Border Radius Generator 🔴 | Rounded Corners & Blobs',
    seoDescription:
      'Create custom rounded corners and organic blobs with our free CSS Border Radius Generator. Visual preview tool for fancy borders and shapes. Copy CSS instantly.',
    icon: <BorderRadiusIcon />,
    category: ToolCategory.CSS,
    keywords: [
      'css border radius generator',
      'rounded corners css',
      'blob generator css',
      'fancy border radius',
      'css shape generator',
      'border radius preview',
      'css corners tool',
    ],
  },
  {
    id: 'text-shadow-generator',
    name: 'Text Shadow Generator',
    description: 'Create beautiful text shadows with precise control over position and blur.',
    seoTitle: 'CSS Text Shadow Generator 👻 | 3D & Glow Text Effects',
    seoDescription:
      'Generate beautiful text shadows, 3D typography, and neon glow effects. Visual CSS Text Shadow Generator with live preview. Copy code for stunning text effects.',
    icon: <TextShadowIcon />,
    category: ToolCategory.CSS,
    keywords: [
      'css text shadow generator',
      'text glow effect css',
      '3d text css generator',
      'multiple text shadows',
      'typography css tool',
      'css text effects',
      'font shadow generator',
    ],
  },
  {
    id: 'glassmorphism-generator',
    name: 'Glassmorphism & Neumorphism Generator',
    description: 'Create modern glassmorphism and neumorphism effects with visual controls.',
    seoTitle: 'Glassmorphism & Neumorphism Generator 🧊 | Frosted Glass CSS',
    seoDescription:
      'Create trendy Glassmorphism (frosted glass) and Neumorphism (soft UI) effects. Visual generator for backdrop-filter, blur, and shadows. Copy modern CSS instantly.',
    icon: <GlassmorphismIcon />,
    category: ToolCategory.CSS,
    keywords: [
      'glassmorphism css generator',
      'frosted glass effect css',
      'neumorphism ui generator',
      'backdrop-filter generator',
      'glass ui design',
      'claymorphism css',
      'soft ui css generator',
    ],
  },
  // Color Tools
  {
    id: 'color-palette-generator',
    name: 'Complementary Color Palette Generator',
    description: 'Generate beautiful color palettes from a base color including complementary, hex, and harmonious schemes.',
    seoTitle: 'Color Palette Generator 🎨 | Complementary & Hex Color Schemes',
    seoDescription:
      'Free complementary color palette generator. Create beautiful hex color schemes, monochromatic, analogous, and triadic palettes from any base color. Perfect for designers.',
    icon: <PaletteIcon />,
    category: ToolCategory.COLOR,
    keywords: [
      'color palette generator',
      'complementary color palette generator',
      'hex color palette generator',
      'color scheme generator',
      'design color combinations',
      'monochromatic color palette',
      'complementary colors',
      'color wheel tool',
      'triadic color generator',
    ],
  },
  {
    id: 'color-theme-wheel',
    name: 'Color Wheel',
    description:
      'Interactive color wheel to generate color themes with harmony presets (analogous, complementary, triadic, and more).',
    seoTitle: 'Color Wheel 🎡 | Interactive Color Theme Generator Online',
    seoDescription:
      'Free interactive color wheel to design beautiful color themes. Choose analogous, complementary, and triadic color schemes. Export as CSS variables or JSON.',
    icon: <PaletteIcon />,
    category: ToolCategory.COLOR,
    keywords: [
      'color wheel',
      'color wheel tool',
      'interactive color wheel',
      'color harmony generator',
      'triadic color scheme',
      'analogous colors',
      'color picker online',
      'ui color palette generator',
      'color theme generator',
    ],
  },
  {
    id: 'css-color-code-converter',
    name: 'CSS Color Code Converter',
    description: 'Convert between HEX/HEXA, RGB/RGBA, HSL/HSLA, and CSS color keywords.',
    seoTitle: 'CSS Color Code Converter 🎨 | HEX, RGB & HSL Converter',
    seoDescription:
      'Instantly convert between HEX, RGB, and HSL color codes with our free online tool. Supports alpha channels (transparency) and CSS color names. Perfect for developers and designers.',
    icon: <ColorIcon />,
    category: ToolCategory.COLOR,
    keywords: [
      'hex to rgb converter',
      'hsl to hex',
      'rgba color picker',
      'css color converter',
      'color code translator',
      'hex to hsl',
    ],
  },
  {
    id: 'video-compressor',
    name: 'Video Compressor',
    description: 'Reduce video file size without significant quality loss.',
    seoTitle: 'Video Compressor Free 🗜️ | Reduce MP4 Size Online',
    seoDescription:
      'Compress video files online for free without losing quality. Reduce MP4, MOV, AVI size for WhatsApp, Email, or Web. Fast and secure.',
    icon: <VideoCompressorIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      'video compressor online',
      'reduce video size',
      'compress mp4',
      'video size reducer',
      'shrink video file',
      'free video compression',
      'reduce video file size free',
      'compress video for whatsapp',
    ],
  },
  {
    id: 'video-to-audio-converter',
    name: 'Video to Audio Converter',
    description: 'Extract audio tracks from video files as MP3.',
    seoTitle: 'Video to Audio Converter 🎵 | MP4 to MP3 - Free Online',
    seoDescription:
      'Convert video to audio instantly. Extract MP3 from MP4, WAV from MOV. Free online video to sound converter. No signup required.',
    icon: <VideoToAudioIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      'video to audio',
      'convert mp4 to mp3',
      'extract audio from video',
      'video to sound converter',
      'mp4 to audio',
      'online audio extractor',
      'mp4 to mp3 converter',
    ],
  },
  {
    id: 'gif-maker',
    name: 'GIF Maker',
    description: 'Convert video clips into animated GIFs.',
    seoTitle: 'Video to GIF Converter 🎞️ | Make Animated GIFs Free',
    seoDescription:
      'Turn video clips into animated GIFs instantly. Convert MP4 to GIF online. Customize start/end time and size. High quality and free.',
    icon: <GifMakerIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      'gif maker online',
      'video to gif',
      'create gif from video',
      'mp4 to gif',
      'make animated gif',
      'free gif generator',
      'video to gif converter',
    ],
  },
  {
    id: 'trim-video',
    name: 'Trim Video',
    description: 'Cut and trim video files to desired length.',
    seoTitle: 'Trim Video Online Free ✂️ | Cut MP4, MOV - No Watermark',
    seoDescription:
      'Trim and cut video files online for free. Support for MP4, MOV, AVI. Fast, secure, and no watermark. Remove unwanted parts instantly in your browser.',
    icon: <TrimVideoIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      'trim video online',
      'video cutter',
      'cut mp4 video',
      'online video splitter',
      'video clipper',
      'free video trimmer',
      'trim mp4 video',
      'mp4 trimmer',
      'trim mp4 file',
      'mp4 length editor',
      'trim video no watermark',
      'cut video online free',
    ],
  },
  {
    id: 'format-converter',
    name: 'Video Format Converter',
    description: 'Convert videos between different formats like MP4, AVI, MOV.',
    seoTitle: 'Video Converter Online 🎞️ | MP4, AVI, MOV, WEBM',
    seoDescription:
      'Free online video converter. Change video format easily. Convert MP4 to AVI, MOV to MP4, and more. No file size limit, no watermark.',
    icon: <FormatConverterIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      'video format converter',
      'convert mp4 to avi',
      'mov to mp4',
      'change video format',
      'online video transcoder',
      'free video converter',
      'video converter online',
    ],
  },
  {
    id: 'video-thumbnail-extractor',
    name: 'Video Thumbnail Extractor',
    description: 'Extract image thumbnails from specific timestamps in a video.',
    seoTitle: 'Video Thumbnail Grabber 📸 | Extract Images from Video',
    seoDescription:
      'Extract high-quality JPG/PNG frames from video. Capture video screenshots instantly. Perfect for YouTube thumbnails or previews.',
    icon: <VideoThumbnailIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      'video thumbnail extractor',
      'capture frame from video',
      'video screenshot tool',
      'get image from video',
      'video frame grabber',
      'create thumbnail from video',
      'video to image',
    ],
  },
  {
    id: 'video-mute',
    name: 'Mute Video',
    description: 'Remove audio track from a video file.',
    seoTitle: 'Mute Video Online 🔇 | Remove Audio from MP4 - Free',
    seoDescription:
      'Remove audio from video files instantly. Mute MP4, MOV, and AVI videos online for free. No watermark, processing happens in your browser.',
    icon: <VideoMuteIcon />,
    category: ToolCategory.VIDEO,
    keywords: [
      'mute video online',
      'remove audio from video',
      'silence video',
      'video mute tool',
      'delete sound from video',
      'mp4 muter',
      'mute audio video',
      'mute video',
      'remove sound from mp4',
      'mute mp4 online',
    ],
  },
  {
    id: 'watermark-adder',
    name: 'Watermark Adder',
    description: 'Add image or text watermarks to your photos.',
    seoTitle: 'Watermark Adder © | Add Logo & Text to Photos',
    seoDescription:
      'Protect your images with our free online Watermark Adder. Add text or logo watermarks to photos easily to prevent theft.',
    icon: <WatermarkAdderIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'add watermark online',
      'photo watermark tool',
      'add logo to photo',
      'image copyright protector',
      'free watermark app',
      'watermark images',
    ],
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images by dimensions or percentage.',
    seoTitle: 'Image Resizer 📏 | Resize Photos Online Free',
    seoDescription:
      'Resize images online to any dimension or percentage. Change width and height of JPG, PNG, and WebP images without losing quality.',
    icon: <ImageResizerIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'image resizer',
      'resize photo online',
      'change image size',
      'picture resizer tool',
      'scale image',
      'resize jpg',
    ],
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert images between formats like PNG, JPG, WEBP.',
    seoTitle: 'Image Converter 🖼️ | Convert JPG, PNG, WebP Online',
    seoDescription:
      'Convert images to any format (JPG, PNG, WebP) instantly. Free online image converter with bulk processing support.',
    icon: <ImageConverterIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'image converter online',
      'convert jpg to png',
      'webp converter',
      'change image format',
      'photo file converter',
      'bulk image converter',
    ],
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images to reduce file size while maintaining quality.',
    seoTitle: 'Image Compressor 🗜️ | Reduce Photo Size Online',
    seoDescription:
      'Compress JPG, PNG, and WebP images online. Reduce file size by up to 80% without visible quality loss. Speed up your website.',
    icon: <ImageCompressorIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'image compressor',
      'reduce image size',
      'compress jpg online',
      'optimize images for web',
      'photo size reducer',
      'compress png',
    ],
  },
  {
    id: 'todo-list',
    name: 'To-Do List',
    description: 'A simple to-do list that saves your tasks in the browser.',
    seoTitle: 'Simple To-Do List ✅ | Online & Persistent',
    seoDescription:
      'A clean and simple to-do list that saves your tasks in your browser. Organize your day and stay on track with our free and private To-Do List tool.',
    icon: <TodoIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      'todo list',
      'task manager',
      'checklist',
      'to do list online',
      'task list',
      'productivity tool',
    ],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, secure passwords.',
    seoTitle: 'Strong Password Generator 🔒 | Create Secure Passwords',
    seoDescription:
      'Create random, secure passwords with custom length and characters. Protect your accounts with strong, uncrackable passwords created instantly.',
    icon: <PasswordIcon />,
    category: ToolCategory.CODING,
    keywords: [
      'password generator',
      'secure password creator',
      'random password tool',
      'strong password maker',
      'online password generator',
      'security tool',
    ],
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs.',
    seoTitle: 'QR Code Generator 🏁 | Create Free QR Codes',
    seoDescription:
      'Create custom QR codes for URLs, text, Wi-Fi, and more. Download your high-quality QR code in PNG or SVG format instantly.',
    icon: <QrCodeIcon />,
    category: ToolCategory.IMAGE,
    keywords: [
      'qr code generator',
      'create qr code',
      'free qr maker',
      'url to qr code',
      'custom qr code generator',
      'qr code creator',
    ],
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Calculate the difference between two dates.',
    seoTitle: 'Date Calculator 📅 | Days Between Dates',
    seoDescription:
      'Calculate the exact duration between two dates in years, months, weeks, and days. Perfect for event planning and scheduling.',
    icon: <DateCalcIcon />,
    category: ToolCategory.MATH,
    keywords: [
      'date calculator',
      'days between dates',
      'date difference calculator',
      'time duration calculator',
      'calendar calculator',
      'age between dates',
    ],
  },
  {
    id: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'A timer to help you focus using the Pomodoro Technique.',
    seoTitle: 'Pomodoro Timer Online 🍅 | Focus & Productivity Timer',
    seoDescription:
      'Boost your productivity with our free online Pomodoro Timer. Use the 25-minute work / 5-minute break technique to stay focused and get more done.',
    icon: <PomodoroIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      'pomodoro timer',
      'tomato timer',
      'focus timer',
      'productivity timer',
      'pomodoro technique clock',
      'online study timer',
    ],
  },
  {
    id: 'meme-generator',
    name: 'Meme Generator',
    description: 'Create your own memes with popular templates.',
    seoTitle: 'Online Meme Generator 🐸 | Create Funny Memes',
    seoDescription:
      'Make your own memes with our free online Meme Generator. Upload your images or caption popular templates. fast, funny, and no watermark.',
    icon: <MemeIcon />,
    category: ToolCategory.FUN,
    keywords: [
      'meme generator',
      'make a meme online',
      'meme creator',
      'funny meme maker',
      'caption images',
      'internet memes',
    ],
  },

  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units of measurement.',
    seoTitle: 'Unit Converter ⚖️ | Length, Weight, Temp & More',
    seoDescription:
      'Convert between thousands of units of measurement. Length, weight, temperature, volume, and more with our free online Unit Converter.',
    icon: <UnitConverterIcon />,
    category: ToolCategory.MATH,
    keywords: [
      'unit converter',
      'measurement converter',
      'convert units',
      'metric to imperial',
      'length converter',
      'weight conversion',
    ],
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index.',
    seoTitle: 'BMI Calculator ⚖️ | Check Your Body Mass Index',
    seoDescription:
      'Calculate your Body Mass Index (BMI) instantly. Enter your height and weight to see if you are in a healthy weight range. Free and private.',
    icon: <BmiIcon />,
    category: ToolCategory.MATH,
    keywords: [
      'bmi calculator',
      'body mass index',
      'calculate bmi',
      'healthy weight calculator',
      'bmi chart',
      'weight checker',
    ],
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between different currencies.',
    seoTitle: 'Currency Converter 💱 | Real-Time Exchange Rates',
    seoDescription:
      'Convert between 190+ global currencies with live exchange rates. Fast, accurate, and free online Currency Converter.',
    icon: <CurrencyIcon />,
    category: ToolCategory.MATH,
    keywords: [
      'currency converter',
      'exchange rate calculator',
      'convert money',
      'usd to eur',
      'foreign exchange rates',
      'money converter',
    ],
  },
  {
    id: 'world-clock',
    name: 'World Clock',
    description: 'Check the time in different cities around the world.',
    seoTitle: 'World Clock 🕰️ | Current Time Across the Globe',
    seoDescription:
      'Check the current time in major cities around the world. Track multiple time zones instantly with our free World Clock tool.',
    icon: <WorldClockIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      'world clock',
      'current time world',
      'time zone clock',
      'global time',
      'world time zones',
      'meeting planner',
    ],
  },
  {
    id: 'timers-and-stopwatch',
    name: 'Timers and Stopwatch',
    description: 'A simple timer and stopwatch.',
    seoTitle: 'Online Timer & Stopwatch ⏱️ | Countup & Countdown',
    seoDescription:
      'A simple, full-screen online timer and stopwatch. Set alarms, countdowns, and track laps easily directly in your browser.',
    icon: <TimersIcon />,
    category: ToolCategory.PRODUCTIVITY,
    keywords: [
      'online timer',
      'stopwatch online',
      'countdown timer',
      'alarm clock online',
      'lap timer',
      'web stopwatch',
    ],
  },
  {
    id: 'keyword-density-analyzer',
    name: 'Keyword Density Analyzer',
    description: 'Analyze the keyword density of a text.',
    seoTitle: 'Keyword Density Analyzer 📊 | SEO Content Checker',
    seoDescription:
      'Check the keyword density of your text to avoid stuffing and improve SEO. Analyze word frequency and optimize your content for search engines.',
    icon: <KeywordDensityIcon />,
    category: ToolCategory.TEXT,
    keywords: [
      'keyword density checker',
      'word frequency counter',
      'seo content analyzer',
      'optimize keyword usage',
      'keyword stuffing checker',
      'text analysis tool',
    ],
  },
];

export const CATEGORY_ORDER: ToolCategory[] = [
  ToolCategory.AI,
  ToolCategory.TEXT,
  ToolCategory.IMAGE,
  ToolCategory.CSS,
  ToolCategory.CODING,
  ToolCategory.COLOR,
  ToolCategory.MATH,
  ToolCategory.PRODUCTIVITY,
  ToolCategory.FUN,
  ToolCategory.VIDEO,
  ToolCategory.MISC,
];

export const CATEGORY_URL_MAP: Record<ToolCategory, string> = {
  [ToolCategory.AI]: 'ai',
  [ToolCategory.TEXT]: 'text',
  [ToolCategory.IMAGE]: 'image',
  [ToolCategory.CSS]: 'css',
  [ToolCategory.CODING]: 'coding',
  [ToolCategory.COLOR]: 'color',
  [ToolCategory.MATH]: 'calculator',
  [ToolCategory.PRODUCTIVITY]: 'productivity',
  [ToolCategory.FUN]: 'fun',
  [ToolCategory.VIDEO]: 'video',
  [ToolCategory.MISC]: 'other',
};

export const URL_TO_CATEGORY_MAP: Record<string, ToolCategory> = Object.entries(
  CATEGORY_URL_MAP
).reduce(
  (acc, [key, value]) => {
    acc[value] = key as ToolCategory;
    return acc;
  },
  {} as Record<string, ToolCategory>
);

export const CATEGORY_ICONS: Record<ToolCategory, React.ComponentType<{ className?: string }>> = {
  [ToolCategory.AI]: AiCategoryIcon,
  [ToolCategory.TEXT]: TextCategoryIcon,
  [ToolCategory.IMAGE]: ImageCategoryIcon,
  [ToolCategory.CSS]: CssCategoryIcon,
  [ToolCategory.CODING]: CodeCategoryIcon,
  [ToolCategory.COLOR]: ColorCategoryIcon,
  [ToolCategory.MATH]: MathCategoryIcon,
  [ToolCategory.PRODUCTIVITY]: ProductivityCategoryIcon,
  [ToolCategory.FUN]: FunCategoryIcon,
  [ToolCategory.VIDEO]: VideoCategoryIcon,
  [ToolCategory.MISC]: MiscCategoryIcon,
};

export const CATEGORY_DESCRIPTIONS: Record<ToolCategory, string> = {
  [ToolCategory.AI]: 'Token counters, prompt builders, and AI workflow tools — handle large datasets without wasting AI credits.',
  [ToolCategory.TEXT]: 'Manipulate text, count words, and more.',
  [ToolCategory.IMAGE]: 'Edit, convert, and optimize images.',
  [ToolCategory.CSS]: 'Generate CSS code for your projects.',
  [ToolCategory.CODING]: 'Format, validate, and convert code.',
  [ToolCategory.COLOR]: 'Generate palettes and convert colors.',
  [ToolCategory.MATH]: 'Perform calculations and conversions.',
  [ToolCategory.PRODUCTIVITY]: 'Boost your efficiency with these tools.',
  [ToolCategory.FUN]: 'Have some fun with these generators.',
  [ToolCategory.VIDEO]: 'Edit and convert video files.',
  [ToolCategory.MISC]: 'Various useful tools.',
};

export const CATEGORY_CONTENT: Record<ToolCategory, { introduction: string }> = {
  [ToolCategory.AI]: {
    introduction: 'Free browser-based AI workflow tools — count tokens, build prompts, convert datasets, and compare models. Everything runs locally so your data never leaves your device.',
  },
  [ToolCategory.TEXT]: {
    introduction: 'A collection of tools for text manipulation.',
  },
  [ToolCategory.IMAGE]: { introduction: 'Tools for working with images.' },
  [ToolCategory.CSS]: { introduction: 'Generators for CSS styles.' },
  [ToolCategory.CODING]: {
    introduction: 'Format, validate, and convert code.',
  },
  [ToolCategory.COLOR]: {
    introduction: 'Generate palettes and convert colors.',
  },
  [ToolCategory.MATH]: {
    introduction: 'Perform calculations and conversions.',
  },
  [ToolCategory.PRODUCTIVITY]: {
    introduction: 'Boost your efficiency with these tools.',
  },
  [ToolCategory.FUN]: {
    introduction: 'Have some fun with these generators.',
  },
  [ToolCategory.VIDEO]: { introduction: 'Edit and convert video files.' },
  [ToolCategory.MISC]: { introduction: 'Various useful tools.' },
};

export const TOOL_COMPONENT_MAP: Record<string, string> = {
  // AI Tools
  'ai-token-counter': 'AiTokenCounter',
  'ai-prompt-builder': 'AiPromptBuilder',
  'json-to-prompt': 'JsonToPrompt',
  'csv-to-prompt': 'CsvToPrompt',
  'ai-system-prompt-generator': 'AiSystemPromptGenerator',
  'context-window-calculator': 'ContextWindowCalculator',
  'ai-model-comparator': 'AiModelComparator',
  'prompt-template-library': 'PromptTemplateLibrary',
  'ai-text-summarizer': 'AiTextSummarizer',
  'ai-output-formatter': 'AiOutputFormatter',
  // Text & other tools
  'comma-separator': 'CommaSeparator',
  'case-converter': 'CaseConverter',
  'word-counter': 'WordCounter',
  'lorem-ipsum-generator': 'LoremIpsumGenerator',
  'base64-converter': 'Base64Converter',
  'url-encoder': 'UrlEncoder',
  'json-formatter': 'JsonFormatter',
  'uuid-generator': 'UuidGenerator',
  'password-generator': 'PasswordGenerator',
  'image-to-base64': 'ImageToBase64',
  'text-reverser': 'TextReverser',
  'box-shadow-generator': 'BoxShadowGenerator',
  'css-gradient-generator': 'CssGradientGenerator',
  'border-radius-generator': 'BorderRadiusGenerator',
  'text-shadow-generator': 'TextShadowGenerator',
  'glassmorphism-generator': 'GlassmorphismGenerator',
  'hash-generator': 'HashGenerator',
  'jwt-debugger': 'JwtDebugger',
  'qr-code-generator': 'QrCodeGenerator',
  'markdown-previewer': 'MarkdownPreviewer',
  'date-calculator': 'DateCalculator',
  'diff-checker': 'DiffChecker',
  'pomodoro-timer': 'PomodoroTimer',
  'meme-generator': 'MemeGenerator',
  'regex-tester': 'RegexTester',
  'color-palette-generator': 'ColorPaletteGenerator',
  'color-theme-wheel': 'ColorThemeWheel',
  'unit-converter': 'UnitConverter',
  'bmi-calculator': 'BmiCalculator',
  'todo-list': 'TodoList',
  'currency-converter': 'CurrencyConverter',
  'world-clock': 'WorldClock',
  'timers-and-stopwatch': 'TimersAndStopwatch',
  'json-csv-converter': 'JsonCsvConverter',
  'csv-xlsx-converter': 'CsvXlsxConverter',
  'keyword-density-analyzer': 'KeywordDensityAnalyzer',
  'readability-score-calculator': 'ReadabilityScore',
  'loan-calculator': 'LoanCalculator',
  'timezone-converter': 'TimeZoneConverter',
  'css-color-code-converter': 'CssColorCodeConverter',
  'video-compressor': 'VideoCompressor',
  'video-to-audio-converter': 'VideoToAudioConverter',
  'gif-maker': 'GifMaker',
  'trim-video': 'TrimVideo',
  'format-converter': 'FormatConverter',
  'video-thumbnail-extractor': 'VideoThumbnailExtractor',
  'video-mute': 'VideoMute',
  'watermark-adder': 'WatermarkAdder',
  'image-resizer': 'ImageResizer',
  'image-converter': 'ImageConverter',
  'image-compressor': 'ImageCompressor',
  'json-to-typescript': 'JsonToTypescript',
  'code-to-image': 'CodeToImage',
  'sql-formatter': 'SqlFormatter',
  'cron-generator': 'CronParser',
  'slug-generator': 'SlugGenerator',
  'meta-tag-generator': 'MetaTagGenerator',
  'contrast-checker': 'ContrastChecker',
  'chmod-calculator': 'ChmodCalculator',
  'utm-builder': 'UtmBuilder',
  'aspect-ratio-calculator': 'AspectRatio',
  'css-triangle-generator': 'CssTriangle',
  'xml-formatter': 'XmlFormatter',
  'morse-converter': 'MorseConverter',
  'binary-converter': 'BinaryConverter',
  'password-strength': 'PasswordStrength',
  'string-escaper': 'StringEscaper',
  'percentage-calculator': 'PercentageCalculator',
  'markdown-table-generator': 'MarkdownTable',
  'list-randomizer': 'ListRandomizer',
  'text-cleaner': 'TextCleaner',
  'svg-to-data-uri': 'SvgToDataUri',
  'json-yaml-converter': 'JsonYamlConverter',
  'youtube-thumbnail': 'YouTubeThumbnail',
  'fancy-font-generator': 'FancyFontGenerator',
  'hashtag-extractor': 'HashtagExtractor',
  'image-filters': 'ImageFilters',
  'svg-blob-generator': 'SvgBlobGenerator',
  'svg-wave-generator': 'SvgWaveGenerator',
  'keycode-info': 'KeycodeInfo',
  'screen-info': 'ScreenInfo',
  'text-to-speech': 'TextToSpeech',
  'roman-numeral-converter': 'RomanNumeral',
  'age-calculator': 'AgeCalculator',
  'random-number-generator': 'RandomNumber',
  'duplicate-remover': 'DuplicateRemover',
  'html-entity': 'HtmlEntity',
  'css-cursors': 'CssCursors',
  'device-resolutions': 'DeviceResolutions',
  'lorem-image-generator': 'LoremImage',
  'css-borders': 'CssBorders',
  'css-patterns': 'CssPatterns',
  'signature-pad': 'SignaturePad',
};

export function getToolDetails(toolId: string) {
  const PRIVACY_STATEMENT_DESC =
    'All calculations and data processing for this tool are performed locally in your browser. We do not send any of your data to our servers, ensuring your information remains private and secure.';

  const details = TOOL_DETAILS[toolId];

  if (details) {
    return details;
  }

  return {
    introduction: '',
    howToUse: [],
    features: [],
    privacy: PRIVACY_STATEMENT_DESC,
    explanation: '',
    usageExamples: [],
    underlyingConcept: '',
    faqs: [],
    tip: '',
  };
}
